#!/usr/bin/env python3
"""Freeze the declared V3 diagnostic as a forward-only lifetime tracking scorer.

This artifact is research-only.  It cannot authorize an order, a production
candidate, or a shadow-to-live promotion.  Its sole purpose is to make future
ENTRY_TRIGGERED decisions reproducible while full position lifetimes are
observed without retuning against those future paths.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from .build_dataset import FEATURE_NAMES
from .train import INTERACTIONS, fit_bundle, load_rows


CONFIGURATION = {
    "family": "TRANSITION_INTERACTIONS",
    "l2": 10.0,
    "min_ev": 0.10,
    "max_full_loss": 0.45,
    "min_bank": 0.45,
    "direction_margin": 0.05,
}

INVALIDATION_CANDIDATES = [
    {
        "id": "FROZEN_V3_DIAGNOSTIC",
        "adverse_r_lte": -0.40,
        "transition_score_lte": -0.25,
        "requires": [],
    },
    {
        "id": "STRICT_PRESSURE_RESUMPTION",
        "adverse_r_lte": -0.50,
        "transition_score_lte": -0.35,
        "requires": ["resumption_evidence=false"],
    },
    {
        "id": "STRUCTURAL_REVERSAL_CONFIRMATION",
        "adverse_r_lte": -0.40,
        "transition_score_lte": -0.25,
        "requires": ["m1_plus_m5_trend_aligned<=-1"],
    },
    {
        "id": "EXPANDING_PULLBACK_FAILURE",
        "adverse_r_lte": -0.35,
        "transition_score_lte": -0.30,
        "requires": ["pullback_still_expanding=true", "resumption_evidence=false"],
    },
]


def model_payload(model, names: list[str]) -> dict:
    return model.payload(names)


def write_mqh(payload: dict, path: Path) -> None:
    names = payload["model_feature_names"]
    outcomes = ["full_loss", "bank1", "plus_2", "plus_3", "plus_5", "expected_net_r"]

    def array(name: str, values) -> str:
        rendered = ",".join(format(float(value), ".17g") for value in values)
        return f"double {name}[V3_MODEL_FEATURE_COUNT]={{{rendered}}};\n"

    text = [
        "// Generated by tools.entry_engine_v3.export_lifetime_model.\n",
        "// Research-only forward tracker. It has no order authority.\n",
        "#define V3_MODEL_FEATURE_COUNT %d\n" % len(names),
        "#define V3_BASE_FEATURE_COUNT %d\n" % len(FEATURE_NAMES),
        'const string V3_TRACKING_MODEL_ID="%s";\n' % payload["model_id"],
        "const double V3_MIN_EV=0.10;\n",
        "const double V3_MAX_FULL_LOSS=0.45;\n",
        "const double V3_MIN_BANK1=0.45;\n",
        "const double V3_DIRECTION_MARGIN=0.05;\n",
    ]
    for index, outcome in enumerate(outcomes):
        model = payload["models"][outcome]
        text.append(f"const double V3_INTERCEPT_{index}={format(float(model['intercept']), '.17g')};\n")
        text.append(array(f"V3_MEAN_{index}", [model["means"][name] for name in names]))
        text.append(array(f"V3_SCALE_{index}", [model["scales"][name] for name in names]))
        text.append(array(f"V3_COEF_{index}", [model["coefficients"][name] for name in names]))
    path.write_text("".join(text), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--json", type=Path, required=True)
    parser.add_argument("--mqh", type=Path, required=True)
    args = parser.parse_args()
    rows = load_rows(args.dataset / "observations.csv")
    names = FEATURE_NAMES + [f"{a}__x__{b}" for a, b in INTERACTIONS]
    bundle = fit_bundle(rows, CONFIGURATION["l2"], CONFIGURATION["family"])
    cutoff = max(row["observation_utc"] for row in rows)
    payload = {
        "schema": "ENTRY_ENGINE_V3_LIFETIME_TRACKING_MODEL_V1",
        "model_id": "ENTRY_ENGINE_V3_TRACKING_DIAGNOSTIC_20260918",
        "purpose": "FORWARD_ORDERLESS_FULL_LIFETIME_OBSERVATION_ONLY",
        "production_authority": False,
        "order_capability": False,
        "automatic_promotion": False,
        "training_cutoff_utc": cutoff,
        "training_rows": len(rows),
        "training_opportunities": len({row["opportunity_id"] for row in rows}),
        "configuration": CONFIGURATION,
        "base_feature_names": FEATURE_NAMES,
        "interactions": INTERACTIONS,
        "model_feature_names": names,
        "models": {name: model_payload(model, names) for name, model in bundle.items()},
        "invalidation_candidates": INVALIDATION_CANDIDATES,
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.mqh.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    write_mqh(payload, args.mqh)
    print(json.dumps({"model_id": payload["model_id"], "rows": len(rows), "features": len(names), "cutoff": cutoff}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
