#property strict
#property version "1.100"
#property description "V3.1 isolated Strategy Tester-only controlled performance harness"

#include <SolTrade/Config.mqh>
#include <SolTrade/AccountGuard.mqh>
#include <SolTrade/MarketData.mqh>
#include <SolTrade/RiskEngine.mqh>
#include <SolTrade/StrategyBreakout.mqh>
#include <SolTrade/ExecutionEngine.mqh>
#include <SolTrade/PositionManager.mqh>

input datetime ResetAt=D'2025.01.02 00:00:00';
input datetime EligibleFrom=D'2025.01.16 00:00:00';
input datetime EligibleTo=D'2025.02.05 00:00:00';
input datetime ResearchCutoff=D'2026.08.01 00:00:00';
input string SegmentId="2025_S1";
input ENUM_SOLTRADE_BACKTEST_DATASET Dataset=SOLTRADE_DATASET_DEVELOPMENT;
input ENUM_SOLTRADE_COST_PROFILE CostProfile=SOLTRADE_COST_NORMAL;
input string ExecutionLayer="NATIVE_NORMAL_EXECUTION";
input int ExpectedExecutionMode=0;
input string ExecutionInstanceId="V23-001";
input int ExpectedEvaluationCount=277;
input datetime ExpectedFirstEvaluation=D'2025.01.16 00:00:00';
input string OutputRoot="SolTrade\\Phase6\\V23\\V23-001";

#define V23_MAGIC 2607202601
struct V31Bar { datetime t; double o,h,l,c,ema,atr,mean; };
V31Bar g_bars[];int g_n=0,g_setup_dir=0,g_retest=0;datetime g_setup_t=0,g_last_hour=0,g_first_eval=0,g_final_eval=0,g_max_tick=0,g_max_bar=0;double g_boundary=0;
SolTradeConfig g_config;SolTradeAccountStatus g_account;SolTradeMarketSnapshot g_market;SolTradeRiskStatus g_risk;SolTradeExecutionStatus g_execution;SolTradePositionStatus g_position;
CSolTradeRiskEngine g_risk_engine;CSolTradeExecutionEngine g_execution_engine;CSolTradePositionManager g_position_manager;
int g_events=INVALID_HANDLE,g_transactions=INVALID_HANDLE,g_evaluations=0,g_setups=0,g_confirmations=0,g_expired=0,g_entries=0,g_exits=0,g_spread_blocks=0,g_execution_blocks=0,g_risk_blocks=0,g_daily_pauses=0,g_weekly_pauses=0,g_emergency_stops=0,g_consecutive_pauses=0,g_stop_exits=0,g_donchian_exits=0,g_retest_counts[7];
bool g_preflight=false,g_cutoff=false,g_seal_breach=false,g_tracked_open=false;ulong g_track_ticket=0,g_track_identifier=0;long g_track_type=-1;double g_track_volume=0,g_track_entry=0,g_track_stop=0,g_track_unrealized=0;datetime g_track_observation=0;

string TS(datetime t){return t>0?TimeToString(t,TIME_DATE|TIME_SECONDS):"NONE";}
void Event(string type,string reason,string detail="")
  {if(g_events!=INVALID_HANDLE)FileWrite(g_events,"SOLTRADE_PHASE6_V23_EVENT_V1",TS(TimeCurrent()),SegmentId,SolTradeBacktestDatasetName(Dataset),SolTradeCostProfileName(CostProfile),ExecutionLayer,type,reason,detail);}
void RecordEntry(string record_type,SolTradeExecutionReport &r,int retest_no,datetime confirmation,double atr)
  {if(g_transactions==INVALID_HANDLE)return;ulong pid=r.deal_ticket?((ulong)HistoryDealGetInteger(r.deal_ticket,DEAL_POSITION_ID)):0;FileWrite(g_transactions,"SOLTRADE_PHASE6_V23_TRANSACTION_V1",TS(TimeCurrent()),SegmentId,record_type,TS(r.signal_bar_time),StringFormat("%I64u",pid),r.signal_result,DoubleToString(r.requested_entry,10),DoubleToString(r.actual_entry,10),IntegerToString(r.spread_points),DoubleToString(r.slippage_points,4),DoubleToString(r.volume,8),DoubleToString(r.risk_amount,8),DoubleToString(r.stop_loss,10),StringFormat("%I64u",r.order_ticket),StringFormat("%I64u",r.deal_ticket),IntegerToString((int)r.broker_return_code),"NONE",r.fill_confirmed?"YES":"NO",IntegerToString(retest_no),TS(confirmation),DoubleToString(atr,12));}
void RecordExit(string record_type,SolTradePositionReport &r)
  {if(g_transactions==INVALID_HANDLE)return;FileWrite(g_transactions,"SOLTRADE_PHASE6_V23_TRANSACTION_V1",TS(TimeCurrent()),SegmentId,record_type,TS(r.signal_bar_time),StringFormat("%I64u",r.position_identifier),r.position_direction,DoubleToString(r.requested_close_price,10),DoubleToString(r.actual_close_price,10),"0",DoubleToString(r.slippage_points,4),DoubleToString(r.volume,8),"0","0",StringFormat("%I64u",r.order_ticket),StringFormat("%I64u",r.deal_ticket),IntegerToString((int)r.broker_return_code),r.exit_reason_code,r.fill_confirmed?"YES":"NO","0","NONE","0");}

void LoadConfig()
  {
   g_config.strategy_version="TREND_BREAKOUT_V3_RETEST_HOLD_1_1";g_config.approved_strategy_version="";g_config.risk_profile="CONSERVATIVE_V1";g_config.approved_risk_profile="";g_config.magic_number=V23_MAGIC;g_config.symbol="EURUSD";g_config.timeframe=PERIOD_H1;g_config.minimum_history_bars=300;g_config.max_tick_age_seconds=120;g_config.max_spread_points=30;g_config.max_spread_atr_percent=20.0;g_config.max_slippage_points=10;g_config.risk_per_trade_percent=.25;g_config.daily_loss_limit_percent=1.0;g_config.weekly_loss_limit_percent=2.5;g_config.emergency_drawdown_percent=5.0;g_config.production_baseline_equity=0;g_config.consecutive_loss_limit=3;g_config.reset_emergency_lock=false;g_config.expected_environment=SOLTRADE_ENV_BACKTEST;g_config.enable_demo_execution=false;g_config.enable_position_management=false;g_config.approved_demo_account=0;g_config.allow_live_trading=false;g_config.approved_live_account=0;g_config.emergency_stop=false;g_config.enable_backtest_research=true;g_config.enable_backtest_execution=true;g_config.enable_backtest_position_management=true;g_config.research_manifest_id="PHASE6-V23-CONTROLLED-PRESEAL-DEVELOPMENT";g_config.execution_instance_id=ExecutionInstanceId;g_config.research_dataset=Dataset;g_config.research_cost_profile=CostProfile;g_config.research_start_inclusive=EligibleFrom;g_config.research_end_exclusive=EligibleTo;g_config.research_history_fingerprint="b212f8986bb69ffd2bdfdbf8e98f270d75cf6672bc51d4e601c311064c418bad";g_config.research_latency_fingerprint="e301e77895e8f095d485b00bd1b5da9f10f07d6c8b6ae9162048a7643ddf4dfe";g_config.research_latency_sample_count=30;g_config.research_frozen_delay_ms=200;g_config.research_source_commit="bac30558aa338b02220ebbb33b67d6b6dd1dc375";g_config.research_build_fingerprint="bcddb6b3d3ed43f9abad9fdb1793fdae11f0d2f34a76b637844345f64bfd5e95";g_config.research_expected_terminal_build=6090;g_config.research_expected_broker_server="FPMarketsSC-Demo";g_config.research_expected_initial_deposit=10000;g_config.research_expected_deposit_currency="USD";g_config.research_expected_leverage=30;g_config.research_expected_trading_input_hash="bcddb6b3d3ed43f9abad9fdb1793fdae11f0d2f34a76b637844345f64bfd5e95";g_config.research_state_root="SolTradeBot\\phase6-v23-state\\"+ExecutionInstanceId;g_config.research_artifact_root="SolTradeBot\\phase6-v23-artifacts\\"+ExecutionInstanceId;g_config.enable_csv_journal=true;g_config.journal_directory="SolTradeBot\\phase6-v23-journal\\"+ExecutionInstanceId;g_config.risk_state_directory=g_config.research_state_root;g_config.execution_state_directory=g_config.research_state_root;g_config.enable_dashboard=false;g_config.dashboard_refresh_seconds=1;
  }
bool Preflight(string &reason)
  {
   reason="";if(!MQLInfoInteger(MQL_TESTER)||MQLInfoInteger(MQL_OPTIMIZATION)){reason="TESTER_ONLY_OPTIMIZATION_PROHIBITED";return false;}if(_Symbol!="EURUSD"||_Period!=PERIOD_H1||AccountInfoString(ACCOUNT_SERVER)!="FPMarketsSC-Demo"||(int)TerminalInfoInteger(TERMINAL_BUILD)!=6090||AccountInfoString(ACCOUNT_CURRENCY)!="USD"||(int)AccountInfoInteger(ACCOUNT_LEVERAGE)!=30||MathAbs(AccountInfoDouble(ACCOUNT_BALANCE)-10000)>0.01){reason="FROZEN_TESTER_ENVIRONMENT_DIFFERS";return false;}if(ResetAt<=0||EligibleFrom<ResetAt||EligibleTo<=EligibleFrom||EligibleTo>ResearchCutoff||ResearchCutoff!=D'2026.08.01 00:00:00'||ExpectedEvaluationCount<=0||ExpectedFirstEvaluation<EligibleFrom||ExpectedFirstEvaluation>=EligibleTo){reason="FROZEN_BOUNDARY_INVALID";return false;}if((ExpectedExecutionMode==0&&ExecutionLayer!="NATIVE_NORMAL_EXECUTION")||(ExpectedExecutionMode==200&&ExecutionLayer!="FIXED_DELAY_200_MS")||(ExpectedExecutionMode!=0&&ExpectedExecutionMode!=200)){reason="EXECUTION_AXIS_INVALID";return false;}if(MathAbs(SymbolInfoDouble(_Symbol,SYMBOL_SWAP_LONG)-(-9.71))>1e-8||MathAbs(SymbolInfoDouble(_Symbol,SYMBOL_SWAP_SHORT)-4.50)>1e-8||(int)SymbolInfoInteger(_Symbol,SYMBOL_SWAP_MODE)!=1||(int)SymbolInfoInteger(_Symbol,SYMBOL_SWAP_ROLLOVER3DAYS)!=3){reason="FROZEN_SWAP_DIFFERS";return false;}if(FileIsExist(OutputRoot+"\\run-summary.csv",FILE_COMMON)){reason="OUTPUT_COLLISION";return false;}return ValidateSolTradeConfig(g_config,reason);
  }
bool Compute(V31Bar &b)
  {
   if(g_n==200){double x=0;for(int i=0;i<200;i++)x+=g_bars[i].c;b.ema=x/200;}else if(g_n>200)b.ema=b.c*(2.0/201.0)+g_bars[g_n-2].ema*(199.0/201.0);
   if(g_n==14){double x=0;for(int i=0;i<14;i++){double tr=g_bars[i].h-g_bars[i].l;if(i>0)tr=MathMax(tr,MathMax(MathAbs(g_bars[i].h-g_bars[i-1].c),MathAbs(g_bars[i].l-g_bars[i-1].c)));x+=tr;}b.atr=x/14;}else if(g_n>14){double tr=MathMax(b.h-b.l,MathMax(MathAbs(b.h-g_bars[g_n-2].c),MathAbs(b.l-g_bars[g_n-2].c)));b.atr=(g_bars[g_n-2].atr*13+tr)/14;}
   if(g_n>=114){double x=0;for(int i=g_n-101;i<=g_n-2;i++)x+=g_bars[i].atr;b.mean=x/100;}return true;
  }
bool Regime(V31Bar &b){return b.atr>0&&b.mean>0&&b.atr/b.mean>=.5&&b.atr/b.mean<=2.0;}
int SetupCandidate(V31Bar &b,double &bound)
  {if(g_n<300||!Regime(b))return 0;double hi=-DBL_MAX,lo=DBL_MAX;for(int i=g_n-21;i<=g_n-2;i++){hi=MathMax(hi,g_bars[i].h);lo=MathMin(lo,g_bars[i].l);}if(b.c>hi&&b.c>b.ema){bound=hi;return 1;}if(b.c<lo&&b.c<b.ema){bound=lo;return -1;}return 0;}
void CreateSetup(V31Bar &b,int dir,double bound){g_setup_dir=dir;g_setup_t=b.t;g_boundary=bound;g_retest=0;g_setups++;Event("SETUP","CREATED","direction="+(dir>0?"BUY":"SELL")+";boundary="+DoubleToString(bound,10));}
void RefreshFoundation()
  {EvaluateSolTradeAccountSafety(g_config,g_account);RefreshSolTradeMarketData(g_config,g_market);string reason="";g_risk_engine.Refresh(TimeCurrent(),AccountInfoDouble(ACCOUNT_EQUITY),reason);g_risk_engine.GetStatus(g_risk);g_execution_engine.RefreshExposure();g_execution_engine.GetStatus(g_execution);g_position_manager.Refresh(reason);g_position_manager.GetStatus(g_position);}
void TrackPosition()
  {g_track_observation=TimeCurrent();g_tracked_open=false;for(int i=0;i<PositionsTotal();i++){ulong t=PositionGetTicket(i);if(t==0||(ulong)PositionGetInteger(POSITION_MAGIC)!=V23_MAGIC||PositionGetString(POSITION_SYMBOL)!="EURUSD")continue;g_tracked_open=true;g_track_ticket=t;g_track_identifier=(ulong)PositionGetInteger(POSITION_IDENTIFIER);g_track_type=PositionGetInteger(POSITION_TYPE);g_track_volume=PositionGetDouble(POSITION_VOLUME);g_track_entry=PositionGetDouble(POSITION_PRICE_OPEN);g_track_stop=PositionGetDouble(POSITION_SL);g_track_unrealized=PositionGetDouble(POSITION_PROFIT)+PositionGetDouble(POSITION_SWAP);break;}}
void ProcessClose(V31Bar &b)
  {
   if(!g_position.position_present||g_n<11)return;double hi=-DBL_MAX,lo=DBL_MAX;for(int i=g_n-11;i<=g_n-2;i++){hi=MathMax(hi,g_bars[i].h);lo=MathMin(lo,g_bars[i].l);}bool close=(g_position.position_type==POSITION_TYPE_BUY&&b.c<lo)||(g_position.position_type==POSITION_TYPE_SELL&&b.c>hi);if(!close)return;SolTradeStrategySignal s;ResetSolTradeStrategySignal(s);s.evaluated=true;s.valid=true;s.signal_bar_time=b.t;s.exit_signal=g_position.position_type==POSITION_TYPE_BUY?SOLTRADE_EXIT_LONG:SOLTRADE_EXIT_SHORT;s.exit_reason_code="DONCHIAN_10_EXIT";s.exit_reason="V3.1 completed-close Donchian-10 structural exit";SolTradePositionReport r;g_position_manager.ProcessClose(s,SOLTRADE_CLOSE_STRATEGY,g_account,g_market,r);if(r.evaluated){Event(r.event_type,r.reason_code,r.reason);RecordExit("EXIT_ATTEMPT",r);}g_position_manager.GetStatus(g_position);
  }
void ProcessEntry(V31Bar &b,int dir,int retest_no)
  {
   g_confirmations++;g_retest_counts[retest_no]++;double actual=(g_market.ask-g_market.bid)/g_market.point,limit=MathMin(30.0,.20*b.atr/g_market.point);Event("CONFIRMATION","VALID","direction="+(dir>0?"BUY":"SELL")+";retest="+IntegerToString(retest_no)+";spread="+DoubleToString(actual,8)+";limit="+DoubleToString(limit,12));
   if(actual>limit){g_spread_blocks++;Event("ENTRY_BLOCK","SPREAD_EXCEEDS_V31_LIMIT","one_shot_consumed=YES");return;}
   SolTradeStrategySignal s;ResetSolTradeStrategySignal(s);s.evaluated=true;s.valid=true;s.entry_signal=dir>0?SOLTRADE_SIGNAL_BUY:SOLTRADE_SIGNAL_SELL;s.signal_bar_time=b.t;s.signal_open=b.o;s.signal_high=b.h;s.signal_low=b.l;s.signal_close=b.c;s.ema_200=b.ema;s.atr_14=b.atr;s.initial_stop_distance=2*b.atr;s.entry_reason_code="V31_RETEST_HOLD_CONFIRMED";s.entry_reason="Frozen V3.1 retest-hold confirmation; first-tick one-shot";
   if(g_risk.daily_locked){g_daily_pauses++;g_risk_blocks++;}else if(g_risk.weekly_locked){g_weekly_pauses++;g_risk_blocks++;}else if(g_risk.emergency_locked){g_emergency_stops++;g_risk_blocks++;}else if(g_risk.consecutive_locked){g_consecutive_pauses++;g_risk_blocks++;}
   SolTradeExecutionReport r;g_execution_engine.ProcessSignal(s,g_account,g_market,g_risk,false,r);if(r.evaluated){if(r.broker_accepted&&r.deal_ticket!=0)g_entries++;if(!r.broker_accepted){if(r.reason_code=="SPREAD_REJECTED"||r.reason_code=="EXCESSIVE_SPREAD"||r.reason_code=="SPREAD_EXCEEDS_LIMIT")g_spread_blocks++;else if(r.reason_code!="RISK_ENGINE_LOCKED")g_execution_blocks++;}Event(r.event_type,r.reason_code,r.reason);RecordEntry("ENTRY_ATTEMPT",r,retest_no,b.t,b.atr);}g_execution_engine.GetStatus(g_execution);
  }
void ProcessBar(V31Bar &b)
  {
   if(g_n<300||b.t<EligibleFrom||b.t>=EligibleTo)return;if(g_first_eval==0)g_first_eval=b.t;g_final_eval=b.t;g_evaluations++;ProcessClose(b);double candidate_bound=0;int candidate=SetupCandidate(b,candidate_bound);
   if(g_setup_dir!=0){g_retest++;int dir=g_setup_dir;bool touch=dir>0?b.l<=g_boundary:b.h>=g_boundary;bool hold=dir>0?b.c>g_boundary:b.c<g_boundary;bool emaok=dir>0?b.c>b.ema:b.c<b.ema;if(touch&&hold&&emaok&&Regime(b)){ProcessEntry(b,dir,g_retest);g_setup_dir=0;g_setup_t=0;g_boundary=0;g_retest=0;return;}bool wrong=!emaok,opp=candidate!=0&&candidate!=dir;string reason=wrong?"WRONG_EMA_SIDE":opp?"OPPOSITE_BREAKOUT":g_retest>=6?"EXPIRED_SIX_CANDLES":"";if(reason!=""){if(reason=="EXPIRED_SIX_CANDLES")g_expired++;Event("SETUP_CANCEL",reason,"retest="+IntegerToString(g_retest));g_setup_dir=0;g_setup_t=0;g_boundary=0;g_retest=0;if(opp){CreateSetup(b,candidate,candidate_bound);return;}}}
   g_position_manager.GetStatus(g_position);if(!g_position.position_present&&g_setup_dir==0&&candidate!=0)CreateSetup(b,candidate,candidate_bound);
  }
void NewBar()
  {datetime hour=iTime(_Symbol,PERIOD_H1,0);if(hour<=0||hour==g_last_hour)return;g_last_hour=hour;MqlRates rr[1];if(CopyRates(_Symbol,PERIOD_H1,1,1,rr)!=1||rr[0].time<ResetAt||rr[0].time>=EligibleTo||rr[0].time==g_max_bar)return;int z=ArraySize(g_bars);ArrayResize(g_bars,z+1,512);g_bars[z].t=rr[0].time;g_bars[z].o=rr[0].open;g_bars[z].h=rr[0].high;g_bars[z].l=rr[0].low;g_bars[z].c=rr[0].close;g_bars[z].ema=0;g_bars[z].atr=0;g_bars[z].mean=0;g_n=z+1;Compute(g_bars[z]);g_max_bar=rr[0].time;ProcessBar(g_bars[z]);}
void FreezeCutoff(){if(g_cutoff)return;g_cutoff=true;Event("CUTOFF_FROZEN",g_tracked_open?"RIGHT_CENSORED_OPEN_POSITION":"NO_OPEN_POSITION_AT_CUTOFF","eligible_to="+TS(EligibleTo));}
bool WriteCutoff()
  {int h=FileOpen(OutputRoot+"\\cutoff.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(h==INVALID_HANDLE)return false;FileWrite(h,"field","value");FileWrite(h,"classification",g_tracked_open?"RIGHT_CENSORED_OPEN_POSITION":"NO_OPEN_POSITION_AT_CUTOFF");FileWrite(h,"eligible_to",TS(EligibleTo));FileWrite(h,"observation_time",TS(g_track_observation));FileWrite(h,"position_open",g_tracked_open?"YES":"NO");FileWrite(h,"position_ticket",StringFormat("%I64u",g_track_ticket));FileWrite(h,"position_identifier",StringFormat("%I64u",g_track_identifier));FileWrite(h,"position_type",IntegerToString(g_track_type));FileWrite(h,"volume",DoubleToString(g_track_volume,8));FileWrite(h,"entry_price",DoubleToString(g_track_entry,10));FileWrite(h,"stop_loss",DoubleToString(g_track_stop,10));FileWrite(h,"unrealized_result_reporting_only",DoubleToString(g_track_unrealized,8));FileWrite(h,"formal_pnl_included","NO");FileWrite(h,"naturally_closed_trade_included","NO");FileClose(h);return true;}
bool WriteDeals()
  {HistorySelect(ResetAt,TimeCurrent());int h=FileOpen(OutputRoot+"\\deals.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(h==INVALID_HANDLE)return false;FileWrite(h,"deal_ticket","order_ticket","position_identifier","time","time_msc","entry","type","reason","volume","price","profit","commission","swap","fee","magic","symbol","comment","in_research_window");for(int i=0;i<HistoryDealsTotal();i++){ulong d=HistoryDealGetTicket(i);if(d==0||(ulong)HistoryDealGetInteger(d,DEAL_MAGIC)!=V23_MAGIC||HistoryDealGetString(d,DEAL_SYMBOL)!="EURUSD")continue;datetime t=(datetime)HistoryDealGetInteger(d,DEAL_TIME);FileWrite(h,StringFormat("%I64u",d),StringFormat("%I64u",(ulong)HistoryDealGetInteger(d,DEAL_ORDER)),StringFormat("%I64u",(ulong)HistoryDealGetInteger(d,DEAL_POSITION_ID)),TS(t),StringFormat("%I64d",HistoryDealGetInteger(d,DEAL_TIME_MSC)),IntegerToString((int)HistoryDealGetInteger(d,DEAL_ENTRY)),IntegerToString((int)HistoryDealGetInteger(d,DEAL_TYPE)),IntegerToString((int)HistoryDealGetInteger(d,DEAL_REASON)),DoubleToString(HistoryDealGetDouble(d,DEAL_VOLUME),8),DoubleToString(HistoryDealGetDouble(d,DEAL_PRICE),10),DoubleToString(HistoryDealGetDouble(d,DEAL_PROFIT),8),DoubleToString(HistoryDealGetDouble(d,DEAL_COMMISSION),8),DoubleToString(HistoryDealGetDouble(d,DEAL_SWAP),8),DoubleToString(HistoryDealGetDouble(d,DEAL_FEE),8),StringFormat("%I64d",HistoryDealGetInteger(d,DEAL_MAGIC)),HistoryDealGetString(d,DEAL_SYMBOL),HistoryDealGetString(d,DEAL_COMMENT),(t>=EligibleFrom&&t<EligibleTo)?"YES":"NO");}FileClose(h);return true;}
bool WriteSummary()
  {int h=FileOpen(OutputRoot+"\\run-summary.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(h==INVALID_HANDLE)return false;FileWrite(h,"field","value");FileWrite(h,"schema","SOLTRADE_PHASE6_V23_RUN_SUMMARY_V1");FileWrite(h,"execution_instance_id",ExecutionInstanceId);FileWrite(h,"segment_id",SegmentId);FileWrite(h,"dataset",SolTradeBacktestDatasetName(Dataset));FileWrite(h,"cost_profile",SolTradeCostProfileName(CostProfile));FileWrite(h,"execution_layer",ExecutionLayer);FileWrite(h,"expected_execution_mode",ExpectedExecutionMode);FileWrite(h,"reset_at",TS(ResetAt));FileWrite(h,"eligible_from",TS(EligibleFrom));FileWrite(h,"eligible_to",TS(EligibleTo));FileWrite(h,"first_evaluation",TS(g_first_eval));FileWrite(h,"final_evaluation",TS(g_final_eval));FileWrite(h,"indicator_eligible_h1_openings",ExpectedEvaluationCount);FileWrite(h,"exclusive_boundary_unobservable_final_h1",1);FileWrite(h,"expected_processable_completed_h1",ExpectedEvaluationCount-1);FileWrite(h,"evaluations",g_evaluations);FileWrite(h,"setups",g_setups);FileWrite(h,"confirmations",g_confirmations);FileWrite(h,"expired_setups",g_expired);FileWrite(h,"entry_fills",g_entries);FileWrite(h,"exit_fills",g_exits);FileWrite(h,"spread_blocks",g_spread_blocks);FileWrite(h,"execution_blocks",g_execution_blocks);FileWrite(h,"risk_engine_blocks",g_risk_blocks);FileWrite(h,"daily_limit_pauses",g_daily_pauses);FileWrite(h,"weekly_limit_pauses",g_weekly_pauses);FileWrite(h,"emergency_stops",g_emergency_stops);FileWrite(h,"consecutive_loss_pauses",g_consecutive_pauses);FileWrite(h,"stop_loss_exits",g_stop_exits);FileWrite(h,"donchian_exits",g_donchian_exits);for(int i=1;i<=6;i++)FileWrite(h,"retest_"+IntegerToString(i),g_retest_counts[i]);FileWrite(h,"censored_position",g_tracked_open?"YES":"NO");FileWrite(h,"max_tick",TS(g_max_tick));FileWrite(h,"max_completed_h1",TS(g_max_bar));FileWrite(h,"seal_breach",g_seal_breach?"YES":"NO");FileWrite(h,"native_tester_commission_inspection","DEALS_LEDGER_REQUIRED");bool valid=g_preflight&&g_cutoff&&!g_seal_breach&&g_evaluations==ExpectedEvaluationCount-1&&g_first_eval==ExpectedFirstEvaluation;FileWrite(h,"run_evidence_status",valid?"PASS":"FAIL");FileClose(h);return valid;}

int OnInit()
  {ArrayResize(g_bars,0);LoadConfig();string reason="";if(!Preflight(reason)){Print("SOLTRADE_V23_PREFLIGHT_FAILED | ",reason);return INIT_PARAMETERS_INCORRECT;}g_events=FileOpen(OutputRoot+"\\events.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');g_transactions=FileOpen(OutputRoot+"\\transactions.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(g_events==INVALID_HANDLE||g_transactions==INVALID_HANDLE)return INIT_FAILED;FileWrite(g_events,"schema","time","segment_id","dataset","cost_profile","execution_layer","event_type","reason_code","details");FileWrite(g_transactions,"schema","time","segment_id","record_type","signal_bar_time","position_identifier","direction","requested_price","actual_price","spread_points","slippage_points","volume","initial_risk_amount","stop_loss","order_ticket","deal_ticket","broker_retcode","exit_reason","fill_confirmed","retest_candle_number","confirmation_timestamp","confirmation_atr");ResetSolTradeMarketSnapshot(g_market);ResetSolTradeRiskStatus(g_risk);ResetSolTradeExecutionStatus(g_execution);ResetSolTradePositionStatus(g_position);EvaluateSolTradeAccountSafety(g_config,g_account);if(!InitialiseSolTradeMarketData(g_config,g_last_hour,reason)||!g_risk_engine.Initialise(g_config,g_account.account_identifier_hash,TimeCurrent(),AccountInfoDouble(ACCOUNT_EQUITY),reason)||!g_execution_engine.Initialise(g_config,g_account.account_identifier_hash,reason)||!g_position_manager.Initialise(g_config,g_account.account_identifier_hash,reason)){Print("SOLTRADE_V23_ENGINE_INIT_FAILED | ",reason);return INIT_FAILED;}g_preflight=true;Event("PREFLIGHT_PASSED","NONE","tester_only=YES;optimization=NO");return INIT_SUCCEEDED;}
void OnTick()
  {datetime now=TimeCurrent();if(now>=ResearchCutoff){g_seal_breach=true;return;}if(now>=EligibleTo){FreezeCutoff();return;}g_max_tick=now;RefreshFoundation();TrackPosition();NewBar();}
void OnTradeTransaction(const MqlTradeTransaction &t,const MqlTradeRequest &q,const MqlTradeResult &z)
  {if(TimeCurrent()>=EligibleTo)return;SolTradeExecutionReport e;if(g_execution_engine.HandleTradeTransaction(t,e)){Event(e.event_type,e.reason_code,"deal="+StringFormat("%I64u",e.deal_ticket));RecordEntry("ENTRY_TRANSACTION",e,0,0,0);}SolTradePositionReport x;if(g_position_manager.HandleTradeTransaction(t,x)){if(x.fill_confirmed){g_exits++;if(x.exit_reason_code=="DONCHIAN_10_EXIT")g_donchian_exits++;else g_stop_exits++;}Event(x.event_type,x.reason_code,x.exit_reason_code);RecordExit("EXIT_TRANSACTION",x);string reason="";g_risk_engine.RecordClosedOutcome("V23_EXIT_"+StringFormat("%I64u",x.deal_ticket),x.final_profit_loss,TimeCurrent(),AccountInfoDouble(ACCOUNT_EQUITY),reason);g_risk_engine.GetStatus(g_risk);}TrackPosition();}
double OnTester()
  {FreezeCutoff();bool ok=WriteCutoff()&&WriteDeals()&&WriteSummary();if(g_events!=INVALID_HANDLE)FileFlush(g_events);if(g_transactions!=INVALID_HANDLE)FileFlush(g_transactions);Print("SOLTRADE_V23_RUN_RESULT | status=",ok?"PASS":"FAIL"," | instance=",ExecutionInstanceId," | evaluations=",g_evaluations," | entries=",g_entries," | exits=",g_exits," | censored=",g_tracked_open?"YES":"NO"," | seal_breach=",g_seal_breach?"YES":"NO");return ok?1:0;}
void OnDeinit(const int reason){if(g_events!=INVALID_HANDLE)FileClose(g_events);if(g_transactions!=INVALID_HANDLE)FileClose(g_transactions);}
