[CmdletBinding()]
param(
 [string]$TrackerHome='C:\SolTrade\Research\SolTrade-Full-Lifetime-Tracker-V1',
 [string]$EvaluatorHome='C:\SolTrade\Research\SolTrade-Forward-Evidence-Evaluator-V1',
 [string]$ExpectedIdentityPath='',
 [switch]$SelfTest
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version 2.0
$ModelId='ENTRY_ENGINE_V3_TRACKING_DIAGNOSTIC_20260918'
$CandidateIds=@('FROZEN_V3_DIAGNOSTIC','STRICT_PRESSURE_RESUMPTION','STRUCTURAL_REVERSAL_CONFIRMATION','EXPANDING_PULLBACK_FAILURE')
$PerTradeFields=@('schema','sequence_id','sequence_status','model_id','opportunity_id','symbol','session','direction','entry_utc','terminal_utc','lifetime_seconds','initial_r_distance','baseline_final_r','baseline_mfe_r','baseline_mae_r','bank1_reached','baseline_plus_2','baseline_plus_3','baseline_plus_5','structural_stop_utc','runner_stop_utc','terminal_reason','entry_expected_net_r','entry_quality','entry_full_loss_probability','entry_bank1_probability','candidate_id','candidate_fired','candidate_fire_utc','invalidation_r','invalidation_transition_score','causal_evidence_state','candidate_final_r','baseline_eventual_final_r','recovered_to_breakeven','reached_plus_1_after_exit','reached_plus_2_after_exit','reached_plus_3_after_exit','reached_plus_5_after_exit','r_saved_vs_baseline','r_lost_vs_baseline_if_interrupted')
$SummaryFields=@('schema','sequence_id','sequence_status','model_id','candidate_id','eligible_triggered_positions','invalidations','full_minus_1_losses_avoided','full_minus_1_losses_not_avoided','average_losing_r_baseline','average_losing_r_with_invalidation','median_losing_r_baseline','median_losing_r_with_invalidation','total_r_saved_vs_baseline','interrupted_breakeven_recoveries','interrupted_bank1_trades','interrupted_plus_2_trades','interrupted_plus_3_trades','interrupted_plus_5_trades','baseline_total_net_r','invalidation_total_net_r','expectancy_difference_r','max_drawdown_baseline_r','max_drawdown_invalidation_r','max_drawdown_difference_r','profit_factor','average_winner_r','average_loser_r','payoff_ratio','result_without_best_winner_r','result_without_best_day_r','dominant_symbol','symbol_entry_fraction','symbol_absolute_net_r_fraction','dominant_session','session_entry_fraction','session_absolute_net_r_fraction')

function Epoch-Now{[DateTimeOffset]::UtcNow.ToUnixTimeSeconds()}
function Iso-Now{[DateTime]::UtcNow.ToString('o')}
function Sha([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
function N($Value,[double]$Default=0){$parsed=0.0;if($null -ne $Value -and [double]::TryParse([string]$Value,[Globalization.NumberStyles]::Float,[Globalization.CultureInfo]::InvariantCulture,[ref]$parsed)){return $parsed};$Default}
function B($Value){$s=[string]$Value;return $Value -eq $true -or $Value -eq 1 -or $s.ToLowerInvariant() -eq 'true'}
function Csv-Pair([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};$lines=@(Get-Content -LiteralPath $Path -TotalCount 2);if($lines.Count -ne 2){return $null};$lines|ConvertFrom-Csv|Select-Object -First 1}
function Atomic-Text([string]$Path,[string]$Text){$dir=Split-Path -Parent $Path;New-Item -ItemType Directory -Force -Path $dir|Out-Null;$tmp="$Path.tmp";[IO.File]::WriteAllText($tmp,$Text,(New-Object Text.UTF8Encoding($false)));Move-Item -Force -LiteralPath $tmp -Destination $Path}
function Atomic-Json([string]$Path,$Value){Atomic-Text $Path (($Value|ConvertTo-Json -Depth 30)+"`n")}
function Import-TreeCsv([string]$Path){$rows=@();if(Test-Path -LiteralPath $Path){foreach($file in @(Get-ChildItem -LiteralPath $Path -Filter '*.csv' -File -Recurse|Sort-Object FullName)){try{$rows+=@(Import-Csv -LiteralPath $file.FullName)}catch{}}};@($rows)}
function Detail-Map([string]$Text){$map=@{};foreach($part in @($Text -split ';')){if($part -match '='){$bits=$part -split '=',2;$map[$bits[0]]=$bits[1]}};$map}
function Median($Values){$a=@($Values|ForEach-Object{N $_}|Sort-Object);if($a.Count -eq 0){return $null};$m=[int]($a.Count/2);if($a.Count%2){return [double]$a[$m]};return ([double]$a[$m-1]+[double]$a[$m])/2.0}
function Max-Drawdown($Rows,[string]$Key){$equity=0.0;$peak=0.0;$worst=0.0;foreach($row in @($Rows|Sort-Object {[long](N $_.entry_utc)})){$equity+=N $row.$Key;if($equity -gt $peak){$peak=$equity};$dd=$peak-$equity;if($dd -gt $worst){$worst=$dd}};$worst}
function Concentration($Rows,[string]$GroupKey,[string]$PayoffKey){
 if(@($Rows).Count -eq 0){return [ordered]@{dominant='';entry_fraction=$null;absolute_net_r_fraction=$null}}
 $groups=@($Rows|Group-Object -Property $GroupKey);$dominant=$groups|Sort-Object Count,Name -Descending|Select-Object -First 1;$contrib=@();foreach($g in $groups){$sum=($g.Group|Measure-Object -Property $PayoffKey -Sum).Sum;$contrib+=[pscustomobject]@{name=$g.Name;net=[double](N $sum);absolute=[Math]::Abs([double](N $sum))}}
 $largest=$contrib|Sort-Object absolute,name -Descending|Select-Object -First 1;$totalAbs=($contrib|Measure-Object -Property absolute -Sum).Sum
 [ordered]@{dominant=$dominant.Name;entry_fraction=$dominant.Count/@($Rows).Count;largest_absolute_net_r_contributor=$largest.name;absolute_net_r_fraction=if((N $totalAbs)-gt 0){$largest.absolute/(N $totalAbs)}else{$null}}
}
function Payoff-Metrics($Rows,[string]$Key){
 $ordered=@($Rows|Sort-Object {[long](N $_.entry_utc)});$pays=@($ordered|ForEach-Object{N $_.$Key});$wins=@($pays|Where-Object{$_ -gt 0});$losses=@($pays|Where-Object{$_ -lt 0});$total=($pays|Measure-Object -Sum).Sum;if($null -eq $total){$total=0.0};$grossWin=($wins|Measure-Object -Sum).Sum;if($null -eq $grossWin){$grossWin=0.0};$grossLoss=-1*(N (($losses|Measure-Object -Sum).Sum));$avgWin=if($wins.Count){(N $grossWin)/$wins.Count}else{$null};$avgLoss=if($losses.Count){-1*$grossLoss/$losses.Count}else{$null}
 $day=@{};foreach($row in $ordered){$d=[DateTimeOffset]::FromUnixTimeSeconds([long](N $row.entry_utc)).UtcDateTime.ToString('yyyy-MM-dd');if(-not $day.ContainsKey($d)){$day[$d]=0.0};$day[$d]+=N $row.$Key};$bestDay='';$bestDayNet=0.0;if($day.Count){$bestDay=($day.GetEnumerator()|Sort-Object Value,Name -Descending|Select-Object -First 1).Key;$bestDayNet=$day[$bestDay]};$best=if($wins.Count){($wins|Measure-Object -Maximum).Maximum}else{0.0}
 [ordered]@{trades=$ordered.Count;total_net_r=[double]$total;expectancy_r=if($ordered.Count){(N $total)/$ordered.Count}else{$null};max_drawdown_r=Max-Drawdown $ordered $Key;profit_factor=if($grossLoss -gt 0){(N $grossWin)/$grossLoss}else{$null};average_winner_r=$avgWin;average_loser_r=$avgLoss;payoff_ratio=if($null -ne $avgWin -and $null -ne $avgLoss -and $avgLoss -ne 0){$avgWin/[Math]::Abs($avgLoss)}else{$null};result_without_best_winner_r=(N $total)-(N $best);best_day_utc=$bestDay;result_without_best_day_r=(N $total)-(N $bestDayNet);daily_net_r=$day}
}
function Candidate-Summary($Rows,[string]$CandidateId,[string]$SequenceId,[string]$Status){
 $selected=@($Rows|Where-Object{$_.candidate_id -eq $CandidateId -and $_.sequence_status -eq 'CLEAN'});$baselineLosses=@($selected|Where-Object{(N $_.baseline_final_r)-lt 0});$candidateLosses=@($selected|Where-Object{(N $_.candidate_final_r)-lt 0});$full=@($selected|Where-Object{$_.terminal_reason -eq 'INITIAL_STRUCTURAL_STOP'});$avoided=@($full|Where-Object{(B $_.candidate_fired) -and (N $_.candidate_final_r)-gt (N $_.baseline_final_r)});$base=Payoff-Metrics $selected 'baseline_final_r';$causal=Payoff-Metrics $selected 'candidate_final_r';$saved=($selected|ForEach-Object{(N $_.candidate_final_r)-(N $_.baseline_final_r)}|Measure-Object -Sum).Sum;if($null -eq $saved){$saved=0.0};$sym=Concentration $selected 'symbol' 'candidate_final_r';$ses=Concentration $selected 'session' 'candidate_final_r'
 [pscustomobject][ordered]@{schema='SOLTRADE_V3_INVALIDATION_ROLLING_V1';sequence_id=$SequenceId;sequence_status=$Status;model_id=$ModelId;candidate_id=$CandidateId;eligible_triggered_positions=$selected.Count;invalidations=@($selected|Where-Object{B $_.candidate_fired}).Count;full_minus_1_losses_avoided=$avoided.Count;full_minus_1_losses_not_avoided=$full.Count-$avoided.Count;average_losing_r_baseline=if($baselineLosses.Count){(N (($baselineLosses|Measure-Object -Property baseline_final_r -Average).Average))}else{$null};average_losing_r_with_invalidation=if($candidateLosses.Count){(N (($candidateLosses|Measure-Object -Property candidate_final_r -Average).Average))}else{$null};median_losing_r_baseline=Median @($baselineLosses|ForEach-Object{$_.baseline_final_r});median_losing_r_with_invalidation=Median @($candidateLosses|ForEach-Object{$_.candidate_final_r});total_r_saved_vs_baseline=[double](N $saved);interrupted_breakeven_recoveries=@($selected|Where-Object{(B $_.candidate_fired)-and(B $_.recovered_to_breakeven)}).Count;interrupted_bank1_trades=@($selected|Where-Object{(B $_.candidate_fired)-and(B $_.reached_plus_1_after_exit)}).Count;interrupted_plus_2_trades=@($selected|Where-Object{(B $_.candidate_fired)-and(B $_.reached_plus_2_after_exit)}).Count;interrupted_plus_3_trades=@($selected|Where-Object{(B $_.candidate_fired)-and(B $_.reached_plus_3_after_exit)}).Count;interrupted_plus_5_trades=@($selected|Where-Object{(B $_.candidate_fired)-and(B $_.reached_plus_5_after_exit)}).Count;baseline_total_net_r=$base.total_net_r;invalidation_total_net_r=$causal.total_net_r;expectancy_difference_r=if($selected.Count){(N $saved)/$selected.Count}else{$null};max_drawdown_baseline_r=$base.max_drawdown_r;max_drawdown_invalidation_r=$causal.max_drawdown_r;max_drawdown_difference_r=(N $base.max_drawdown_r)-(N $causal.max_drawdown_r);profit_factor=$causal.profit_factor;average_winner_r=$causal.average_winner_r;average_loser_r=$causal.average_loser_r;payoff_ratio=$causal.payoff_ratio;result_without_best_winner_r=$causal.result_without_best_winner_r;result_without_best_day_r=$causal.result_without_best_day_r;dominant_symbol=$sym.dominant;symbol_entry_fraction=$sym.entry_fraction;symbol_absolute_net_r_fraction=$sym.absolute_net_r_fraction;dominant_session=$ses.dominant;session_entry_fraction=$ses.entry_fraction;session_absolute_net_r_fraction=$ses.absolute_net_r_fraction}
}
function Write-Csv([string]$Path,$Rows,[string[]]$Fields){$dir=Split-Path -Parent $Path;New-Item -ItemType Directory -Force -Path $dir|Out-Null;$tmp="$Path.tmp";if(@($Rows).Count){@($Rows)|Select-Object -Property $Fields|Export-Csv -LiteralPath $tmp -NoTypeInformation -Encoding UTF8}else{[IO.File]::WriteAllText($tmp,($Fields -join ',')+"`r`n",(New-Object Text.UTF8Encoding($false)))};Move-Item -Force -LiteralPath $tmp -Destination $Path}

function Integrity-Check($Expected,$Outcomes,$Events,$Observations){
 $checks=New-Object Collections.Generic.List[object];$errors=New-Object Collections.Generic.List[string]
 function Add([string]$Name,[bool]$Passed,$ExpectedValue,$ActualValue){$checks.Add([pscustomobject][ordered]@{name=$Name;passed=$Passed;expected=$ExpectedValue;actual=$ActualValue});if(-not $Passed){$errors.Add("$Name expected=$ExpectedValue actual=$ActualValue")}}
 $trackerSource=Join-Path $TrackerHome 'MQL5\Experts\SolTradeFullLifetimeTrackerV1.mq5';$trackerBinary=$trackerSource.Replace('.mq5','.ex5');$trackerModel=Join-Path $TrackerHome 'MQL5\Experts\SolTradeV3TrackingModel.mqh';$trackerData=Join-Path $TrackerHome 'MQL5\Files\SolTradeFullLifetimeTrackerV1';$candidate=Join-Path $trackerData 'frozen-invalidation-candidates.csv';$manifest=Csv-Pair (Join-Path $trackerData 'manifest.csv');$heartbeat=Csv-Pair (Join-Path $trackerData 'status\heartbeat.csv')
 Add 'tracker_source_sha256' ((Sha $trackerSource)-eq $Expected.tracker_source_sha256) $Expected.tracker_source_sha256 (Sha $trackerSource)
 Add 'tracker_binary_sha256' ((Sha $trackerBinary)-eq $Expected.tracker_binary_sha256) $Expected.tracker_binary_sha256 (Sha $trackerBinary)
 Add 'tracker_model_include_sha256' ((Sha $trackerModel)-eq $Expected.tracker_model_include_sha256) $Expected.tracker_model_include_sha256 (Sha $trackerModel)
 Add 'frozen_model_json_sha256' ((Sha (Join-Path $EvaluatorHome 'frozen-tracking-model.json'))-eq $Expected.frozen_model_json_sha256) $Expected.frozen_model_json_sha256 (Sha (Join-Path $EvaluatorHome 'frozen-tracking-model.json'))
 Add 'candidate_receipt_sha256' ((Sha $candidate)-eq $Expected.candidate_receipt_sha256) $Expected.candidate_receipt_sha256 (Sha $candidate)
 Add 'tracker_heartbeat_present' ($null-ne $heartbeat) 'present' $(if($null-ne $heartbeat){'present'}else{'missing'})
 if($null-ne $heartbeat){Add 'tracker_model_id' ($heartbeat.model_id-eq $Expected.model_id) $Expected.model_id $heartbeat.model_id;Add 'tracker_version' ($heartbeat.tracker_version-eq $Expected.tracker_version) $Expected.tracker_version $heartbeat.tracker_version;Add 'tracker_order_capability' ($heartbeat.order_capability-eq 'false') 'false' $heartbeat.order_capability;Add 'tracker_terminal_trade_allowed' ($heartbeat.terminal_trade_allowed-eq 'false') 'false' $heartbeat.terminal_trade_allowed;Add 'tracker_mql_trade_allowed' ($heartbeat.mql_trade_allowed-eq 'false') 'false' $heartbeat.mql_trade_allowed;Add 'tracker_position_time_limit' ($heartbeat.position_time_limit-eq 'none') 'none' $heartbeat.position_time_limit}
 Add 'tracker_manifest_present' ($null-ne $manifest) 'present' $(if($null-ne $manifest){'present'}else{'missing'})
 if($null-ne $manifest){Add 'manifest_entry_specification' ($manifest.entry_specification-eq 'FROZEN_V3_72_FEATURES_8_INTERACTIONS_THRESHOLDS') 'FROZEN_V3_72_FEATURES_8_INTERACTIONS_THRESHOLDS' $manifest.entry_specification;Add 'manifest_safety_disposition' ($manifest.safety_horizon_disposition-eq 'RIGHT_CENSORED') 'RIGHT_CENSORED' $manifest.safety_horizon_disposition;Add 'manifest_bank_action' ($manifest.bank_action-eq 'PLUS_1R_BANK_50_PERCENT_ONCE') 'PLUS_1R_BANK_50_PERCENT_ONCE' $manifest.bank_action;Add 'manifest_ratchet_deployed' ($manifest.ratchet_deployed-eq 'false') 'false' $manifest.ratchet_deployed}
 $sourceText=if(Test-Path $trackerSource){[IO.File]::ReadAllText($trackerSource)}else{''};$patterns=@('#include\s*<Trade/','\bCTrade\b',('\bOrder'+'Send(?:Async)?\s*\('),'\bMqlTradeRequest\b','\bTRADE_ACTION_','\bPositionClose\s*\(','\bPositionModify\s*\(','\bOrderDelete\s*\(');$hits=@();foreach($pattern in $patterns){if($sourceText-match $pattern){$hits+=$pattern}};Add 'tracker_trade_api_scan' ($hits.Count-eq 0) 'no trade APIs' ($hits-join ';')
 $fpSource='C:\SolTrade\MT5-FP-DEMO\MQL5\Experts\SolTrade\SolTradeFastMultiMarketV2.mq5';$fpBinary=$fpSource.Replace('.mq5','.ex5');Add 'fp_source_sha256' ((Sha $fpSource)-eq $Expected.fp_source_sha256) $Expected.fp_source_sha256 (Sha $fpSource);Add 'fp_binary_sha256' ((Sha $fpBinary)-eq $Expected.fp_binary_sha256) $Expected.fp_binary_sha256 (Sha $fpBinary)
 foreach($fx in @(@('fxify_10k','C:\SolTrade\state\fxify-10k.ini',$Expected.fxify_10k_startup_sha256),@('fxify_100k','C:\SolTrade\state\fxify-100k.ini',$Expected.fxify_100k_startup_sha256))){$text=if(Test-Path $fx[1]){[IO.File]::ReadAllText($fx[1])}else{''};Add "$($fx[0])_startup_sha256" ((Sha $fx[1])-eq $fx[2]) $fx[2] (Sha $fx[1]);Add "$($fx[0])_enabled_zero" ($text-match '(?m)^Enabled=0\r?$') 'Enabled=0' $(if($text-match '(?m)^Enabled=0\r?$'){'Enabled=0'}else{'missing'});Add "$($fx[0])_allow_live_zero" ($text-match '(?m)^AllowLiveTrading=0\r?$') 'AllowLiveTrading=0' $(if($text-match '(?m)^AllowLiveTrading=0\r?$'){'AllowLiveTrading=0'}else{'missing'})}
 $collector='C:\SolTrade\Research\SolTrade-Brain-Collector-V1';$collectorSource=Join-Path $collector 'MQL5\Experts\SolTradeBrainCollectorV1.mq5';$collectorBinary=$collectorSource.Replace('.mq5','.ex5');$collectorHb=Csv-Pair (Join-Path $collector 'MQL5\Files\SolTradeBrainCollectorV1\status\heartbeat.csv');Add 'collector_source_sha256' ((Sha $collectorSource)-eq $Expected.collector_source_sha256) $Expected.collector_source_sha256 (Sha $collectorSource);Add 'collector_binary_sha256' ((Sha $collectorBinary)-eq $Expected.collector_binary_sha256) $Expected.collector_binary_sha256 (Sha $collectorBinary);Add 'collector_heartbeat_present' ($null-ne $collectorHb) 'present' $(if($null-ne $collectorHb){'present'}else{'missing'});if($null-ne $collectorHb){Add 'collector_order_capability' ($collectorHb.order_capability-eq 'false') 'false' $collectorHb.order_capability;Add 'collector_terminal_trade_allowed' ($collectorHb.terminal_trade_allowed-eq 'false') 'false' $collectorHb.terminal_trade_allowed;Add 'collector_mql_trade_allowed' ($collectorHb.mql_trade_allowed-eq 'false') 'false' $collectorHb.mql_trade_allowed}
 $badCensored=@($Outcomes|Where-Object{$_.outcome_status-eq 'RIGHT_CENSORED' -and ((B $_.baseline_final_r_known)-or(B $_.aftermath_complete)-or -not[string]::IsNullOrWhiteSpace([string]$_.baseline_final_r))});Add 'right_censored_known_result_violations' ($badCensored.Count-eq 0) 0 $badCensored.Count
 $badOutcome=@($Outcomes|Where-Object{$_.order_capability -ne 'false' -or $_.completed_bars_only -ne 'true'});Add 'outcome_orderless_completed_bar_flags' ($badOutcome.Count -eq 0) 0 $badOutcome.Count
 $badEvent=@($Events|Where-Object{$_.order_capability -ne 'false'});Add 'event_order_capability_violations' ($badEvent.Count -eq 0) 0 $badEvent.Count
 $badObservation=@($Observations|Where-Object{$_.order_capability -ne 'false' -or $_.completed_bars_only -ne 'true' -or $_.feature_window_ready -ne 'true'});Add 'stale_or_noncausal_observation_violations' ($badObservation.Count -eq 0) 0 $badObservation.Count
 [ordered]@{schema='SOLTRADE_V3_FORWARD_INTEGRITY_V1';sequence_id=$Expected.sequence_id;run_utc=Iso-Now;status=if($errors.Count){'EVIDENCE_CONTAMINATED'}else{'CLEAN'};checks=@($checks|ForEach-Object{$_});errors=@($errors|ForEach-Object{$_});outcome_rows=$Outcomes.Count;event_rows=$Events.Count;observation_rows=$Observations.Count;order_capability=$false}
}

function Build-PerTrade($Outcomes,$Events,$Observations,$Expected,[string]$Status){
 $terminal=@($Outcomes|Where-Object{$_.outcome_status-eq 'TERMINAL' -and $_.baseline_final_r_known-eq 'true' -and $_.aftermath_complete-eq 'true'});$unique=@();foreach($g in @($terminal|Group-Object {"$($_.opportunity_id)|$($_.candidate_id)"})){$unique+=@($g.Group|Sort-Object {[long](N $_.terminal_utc)}|Select-Object -Last 1)};$rows=@()
 foreach($outcome in @($unique|Sort-Object {[long](N $_.entry_utc)},candidate_id)){
  $opp=[string]$outcome.opportunity_id;$candidate=[string]$outcome.candidate_id;$entry=@($Events|Where-Object{$_.opportunity_id-eq $opp -and $_.event-eq 'ENTRY_TRIGGERED'}|Sort-Object {[long](N $_.utc_msc)}|Select-Object -First 1);$invalid=@($Events|Where-Object{$_.opportunity_id-eq $opp -and $_.event-eq 'CAUSAL_INVALIDATION' -and $_.candidate_id-eq $candidate}|Sort-Object {[long](N $_.utc_msc)}|Select-Object -First 1);$entryMap=if($entry.Count){Detail-Map $entry[0].detail}else{@{}};$invObs=$null;if($invalid.Count){$invObs=@($Observations|Where-Object{$_.opportunity_id-eq $opp -and [long](N $_.observation_utc_msc)-eq [long](N $invalid[0].utc_msc)}|Select-Object -Last 1)}
  $evidence='';if($invObs -and @($invObs).Count){$o=$invObs[0];$evidence="pressure_reversal=$($o.pressure_reversal);pullback_expanding=$($o.pullback_expanding);resumption_evidence=$($o.resumption_evidence);m1_state=$($o.m1_state);m5_state=$($o.m5_state);transition_score=$($o.transition_score)"}elseif($invalid.Count){$evidence="event_detail=$($invalid[0].detail);transition_score=$($invalid[0].transition_score)"}
  $base=N $outcome.baseline_final_r;$causal=N $outcome.causal_final_r;$ev=if($entryMap.ContainsKey('expected_net_r')){N $entryMap['expected_net_r']}else{$null};$quality=if($null-ne $ev){1.0/(1.0+[Math]::Exp(-2.0*$ev))}else{$null};$fire=B $outcome.causal_exit_triggered
  $rows+=[pscustomobject][ordered]@{schema='SOLTRADE_V3_PER_TRADE_FORWARD_EVIDENCE_V1';sequence_id=$Expected.sequence_id;sequence_status=$Status;model_id=$Expected.model_id;opportunity_id=$opp;symbol=$outcome.symbol;session=$outcome.session;direction=$outcome.direction;entry_utc=[long](N $outcome.entry_utc);terminal_utc=[long](N $outcome.terminal_utc);lifetime_seconds=[long](N $outcome.lifetime_seconds);initial_r_distance=N $outcome.initial_risk;baseline_final_r=$base;baseline_mfe_r=N $outcome.mfe_r;baseline_mae_r=N $outcome.mae_r;bank1_reached=B $outcome.bank1_reached;baseline_plus_2=((N $outcome.mfe_r)-ge 2);baseline_plus_3=((N $outcome.mfe_r)-ge 3);baseline_plus_5=((N $outcome.mfe_r)-ge 5);structural_stop_utc=[long](N $outcome.terminal_utc);runner_stop_utc=if($outcome.terminal_reason-eq 'RUNNER_STRUCTURAL_STOP'){[long](N $outcome.terminal_utc)}else{''};terminal_reason=$outcome.terminal_reason;entry_expected_net_r=$ev;entry_quality=$quality;entry_full_loss_probability=if($entryMap.ContainsKey('full_loss_probability')){N $entryMap['full_loss_probability']}else{$null};entry_bank1_probability=if($entryMap.ContainsKey('bank1_probability')){N $entryMap['bank1_probability']}else{$null};candidate_id=$candidate;candidate_fired=$fire;candidate_fire_utc=if($fire){[long](N $outcome.causal_exit_utc)}else{''};invalidation_r=if($fire){N $outcome.causal_exit_r}else{$null};invalidation_transition_score=if($invalid.Count){N $invalid[0].transition_score}else{$null};causal_evidence_state=$evidence;candidate_final_r=$causal;baseline_eventual_final_r=$base;recovered_to_breakeven=B $outcome.recovered_to_breakeven;reached_plus_1_after_exit=B $outcome.reached_bank1_after_exit;reached_plus_2_after_exit=B $outcome.reached_plus_2_after_exit;reached_plus_3_after_exit=B $outcome.reached_plus_3_after_exit;reached_plus_5_after_exit=B $outcome.reached_plus_5_after_exit;r_saved_vs_baseline=[Math]::Max(0,$causal-$base);r_lost_vs_baseline_if_interrupted=[Math]::Max(0,$base-$causal)}
 }
 @($rows)
}

function Entry-Summary($Rows,$Events,$Expected){
 $base=@($Rows|Where-Object{$_.candidate_id-eq $CandidateIds[0]}|Sort-Object entry_utc);$detected=@($Events|Where-Object{$_.event-eq 'OPPORTUNITY_DETECTED'}|Group-Object opportunity_id);$entered=@($Events|Where-Object{$_.event-eq 'ENTRY_TRIGGERED'}|Group-Object opportunity_id);$abandoned=@($Events|Where-Object{$_.event-eq 'OPPORTUNITY_ABANDONED'}|Group-Object opportunity_id);$metrics=Payoff-Metrics $base 'baseline_final_r';$calibration=@()
 foreach($band in @($Expected.quality_bands)){$low=N $band[0];$high=N $band[1];$group=@($base|Where-Object{$null-ne $_.entry_quality -and (N $_.entry_quality)-ge $low -and (N $_.entry_quality)-lt $high});if($group.Count){$calibration+=[pscustomobject][ordered]@{quality_low=$low;quality_high=$high;completed_entries=$group.Count;average_net_r=(N (($group|Measure-Object -Property baseline_final_r -Average).Average));full_loss_rate=@($group|Where-Object{$_.terminal_reason-eq 'INITIAL_STRUCTURAL_STOP'}).Count/$group.Count;bank1_rate=@($group|Where-Object{B $_.bank1_reached}).Count/$group.Count;plus_2_rate=@($group|Where-Object{B $_.baseline_plus_2}).Count/$group.Count;plus_3_rate=@($group|Where-Object{B $_.baseline_plus_3}).Count/$group.Count;plus_5_rate=@($group|Where-Object{B $_.baseline_plus_5}).Count/$group.Count}}}
 [ordered]@{schema='SOLTRADE_V3_ENTRY_FORWARD_SUMMARY_V1';sequence_id=$Expected.sequence_id;sequence_status='CLEAN';model_id=$Expected.model_id;generated_utc=Iso-Now;opportunities_detected=$detected.Count;wait_state_count=$detected.Count;wait_definition='Every OPPORTUNITY_DETECTED enters WAIT_FOR_TRANSITION before ENTER or ABANDON';enter_count=$entered.Count;abandon_count=$abandoned.Count;currently_unresolved_opportunities=[Math]::Max(0,$detected.Count-$entered.Count-$abandoned.Count);long_count=@($entered|Where-Object{$_.Group[0].direction-eq 'LONG'}).Count;short_count=@($entered|Where-Object{$_.Group[0].direction-eq 'SHORT'}).Count;known_completed_positions=$base.Count;right_censored_positions=@($Events|Where-Object{$_.event-eq 'RIGHT_CENSORED'}|Group-Object opportunity_id).Count;full_losses=@($base|Where-Object{$_.terminal_reason-eq 'INITIAL_STRUCTURAL_STOP'}).Count;full_loss_rate=if($base.Count){@($base|Where-Object{$_.terminal_reason-eq 'INITIAL_STRUCTURAL_STOP'}).Count/$base.Count}else{$null};bank1_count=@($base|Where-Object{B $_.bank1_reached}).Count;bank1_rate=if($base.Count){@($base|Where-Object{B $_.bank1_reached}).Count/$base.Count}else{$null};plus_2_count=@($base|Where-Object{B $_.baseline_plus_2}).Count;plus_2_rate=if($base.Count){@($base|Where-Object{B $_.baseline_plus_2}).Count/$base.Count}else{$null};plus_3_count=@($base|Where-Object{B $_.baseline_plus_3}).Count;plus_3_rate=if($base.Count){@($base|Where-Object{B $_.baseline_plus_3}).Count/$base.Count}else{$null};plus_5_count=@($base|Where-Object{B $_.baseline_plus_5}).Count;plus_5_rate=if($base.Count){@($base|Where-Object{B $_.baseline_plus_5}).Count/$base.Count}else{$null};net_r=$metrics.total_net_r;expectancy_r=$metrics.expectancy_r;max_drawdown_r=$metrics.max_drawdown_r;result_without_best_winner_r=$metrics.result_without_best_winner_r;result_without_best_day_r=$metrics.result_without_best_day_r;quality_definition='1/(1+exp(-2*entry_expected_net_r))';quality_calibration_bands=$calibration;development_search_rerun=$false;tuning_enabled=$false;promotion_authorized=$false}
}

function Self-Test{
 $r=@(
  [pscustomobject]@{sequence_status='CLEAN';candidate_id='FROZEN_V3_DIAGNOSTIC';candidate_fired=$true;baseline_final_r=-1.0;candidate_final_r=-0.4;entry_utc=1000;terminal_reason='INITIAL_STRUCTURAL_STOP';symbol='EURUSD.r';session='LONDON';recovered_to_breakeven=$false;reached_plus_1_after_exit=$false;reached_plus_2_after_exit=$false;reached_plus_3_after_exit=$false;reached_plus_5_after_exit=$false},
  [pscustomobject]@{sequence_status='CLEAN';candidate_id='FROZEN_V3_DIAGNOSTIC';candidate_fired=$true;baseline_final_r=3.0;candidate_final_r=-0.4;entry_utc=2000;terminal_reason='RUNNER_STRUCTURAL_STOP';symbol='XAUUSD.r';session='NEW_YORK';recovered_to_breakeven=$true;reached_plus_1_after_exit=$true;reached_plus_2_after_exit=$true;reached_plus_3_after_exit=$true;reached_plus_5_after_exit=$false}
 );$s=Candidate-Summary $r 'FROZEN_V3_DIAGNOSTIC' 'SELF_TEST' 'CLEAN';if($s.eligible_triggered_positions-ne 2){throw 'self-test eligible count'};if($s.full_minus_1_losses_avoided-ne 1){throw 'self-test loss avoided'};if([Math]::Abs((N $s.total_r_saved_vs_baseline)-(-2.8))-gt 1e-9){throw 'self-test total delta'};if($s.interrupted_plus_3_trades-ne 1){throw 'self-test interrupted tail'};[ordered]@{schema='SOLTRADE_V3_FORWARD_EVALUATOR_SELF_TEST_V1';status='PASS';tests=4;order_capability=$false}|ConvertTo-Json -Depth 5
}

if($SelfTest){Self-Test;exit 0}
if([string]::IsNullOrWhiteSpace($ExpectedIdentityPath)){$ExpectedIdentityPath=Join-Path $EvaluatorHome 'expected-identities.json'}
$output=Join-Path $EvaluatorHome 'output';$stateDir=Join-Path $EvaluatorHome 'state';$statusDir=Join-Path $EvaluatorHome 'status';New-Item -ItemType Directory -Force -Path $output,$stateDir,$statusDir,(Join-Path $output 'daily')|Out-Null
$lockPath=Join-Path $stateDir 'evaluator.lock';$lock=$null
try{$lock=[IO.File]::Open($lockPath,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch{exit 0}
try{
 $Expected=Get-Content -Raw -LiteralPath $ExpectedIdentityPath|ConvertFrom-Json;$trackerData=Join-Path $TrackerHome 'MQL5\Files\SolTradeFullLifetimeTrackerV1';$outcomes=@(Import-TreeCsv (Join-Path $trackerData 'outcomes')|Where-Object{$_.PSObject.Properties.Name -contains 'outcome_status'});$events=@(Import-TreeCsv (Join-Path $trackerData 'events')|Where-Object{$_.PSObject.Properties.Name -contains 'event'});$observations=@(Import-TreeCsv (Join-Path $trackerData 'lifetime_observations')|Where-Object{$_.PSObject.Properties.Name -contains 'observation_utc_msc'});$integrity=Integrity-Check -Expected $Expected -Outcomes $outcomes -Events $events -Observations $observations
 $sequencePath=Join-Path $stateDir 'sequence.json';$sequence=$null;if(Test-Path $sequencePath){try{$sequence=Get-Content -Raw -LiteralPath $sequencePath|ConvertFrom-Json}catch{$sequence=$null}};if($null-eq $sequence){$sequence=[pscustomobject][ordered]@{schema='SOLTRADE_V3_FORWARD_SEQUENCE_V1';sequence_id=$Expected.sequence_id;started_utc=Iso-Now;status='CLEAN';contamination_detected_utc=$null;contamination_reasons=@();last_run_utc=$null}}
 $reasons=New-Object Collections.Generic.List[string];foreach($x in @($sequence.contamination_reasons)){$reasons.Add([string]$x)};if($sequence.sequence_id-ne $Expected.sequence_id){$reasons.Add("sequence_id expected=$($Expected.sequence_id) actual=$($sequence.sequence_id)")};foreach($x in @($integrity.errors)){$reasons.Add([string]$x)};$distinct=@($reasons|Select-Object -Unique);if($sequence.status-eq 'EVIDENCE_CONTAMINATED' -or $distinct.Count){$sequence.status='EVIDENCE_CONTAMINATED';if($null-eq $sequence.contamination_detected_utc){$sequence.contamination_detected_utc=Iso-Now};$sequence.contamination_reasons=$distinct;$integrity.status='EVIDENCE_CONTAMINATED';$integrity.errors=$distinct}else{$sequence.status='CLEAN'};$sequence.last_run_utc=Iso-Now;Atomic-Json $sequencePath $sequence;Atomic-Json (Join-Path $output 'integrity-receipt.json') $integrity
 if($sequence.status-eq 'EVIDENCE_CONTAMINATED'){$heartbeat=[ordered]@{schema='SOLTRADE_V3_FORWARD_EVALUATOR_HEARTBEAT_V1';status='EVIDENCE_CONTAMINATED';sequence_id=$Expected.sequence_id;utc=Epoch-Now;completed_positions_evaluated=0;integrity_errors=$distinct;order_capability=$false;deployment_capability=$false};Atomic-Json (Join-Path $statusDir 'heartbeat.json') $heartbeat;$snap=[ordered]@{schema='SOLTRADE_V3_FORWARD_DAILY_SNAPSHOT_V1';status='EVIDENCE_CONTAMINATED';generated_utc=Iso-Now;sequence=$sequence;integrity=$integrity;results_included=$false};Atomic-Json (Join-Path (Join-Path $output 'daily') ((Get-Date).ToUniversalTime().ToString('yyyyMMdd')+'-snapshot.json')) $snap;exit 2}
 $perTrade=Build-PerTrade $outcomes $events $observations $Expected 'CLEAN';Write-Csv (Join-Path $output 'per-trade-evidence.csv') $perTrade $PerTradeFields;$summaries=@();foreach($id in $CandidateIds){$summaries+=Candidate-Summary $perTrade $id $Expected.sequence_id 'CLEAN'};Write-Csv (Join-Path $output 'rolling-invalidation-summary.csv') $summaries $SummaryFields;$summaryPayload=[ordered]@{schema='SOLTRADE_V3_INVALIDATION_ROLLING_SET_V1';sequence_id=$Expected.sequence_id;sequence_status='CLEAN';model_id=$Expected.model_id;generated_utc=Iso-Now;candidate_selection_performed=$false;recommendation_emitted=$false;candidates=$summaries};Atomic-Json (Join-Path $output 'rolling-invalidation-summary.json') $summaryPayload;$entrySummary=Entry-Summary $perTrade $events $Expected;Atomic-Json (Join-Path $output 'rolling-v3-entry-summary.json') $entrySummary
 $completed=@($perTrade|Where-Object{$_.candidate_id-eq $CandidateIds[0]}).Count;$heartbeat=[ordered]@{schema='SOLTRADE_V3_FORWARD_EVALUATOR_HEARTBEAT_V1';status=if($completed){'EVALUATING_FORWARD_EVIDENCE'}else{'WAITING_FOR_FIRST_COMPLETED_HYPOTHETICAL_TRADE'};sequence_id=$Expected.sequence_id;utc=Epoch-Now;completed_positions_evaluated=$completed;candidate_rows=@($perTrade).Count;integrity_status='CLEAN';order_capability=$false;deployment_capability=$false;tuning_enabled=$false};Atomic-Json (Join-Path $statusDir 'heartbeat.json') $heartbeat;$snapshot=[ordered]@{schema='SOLTRADE_V3_FORWARD_DAILY_SNAPSHOT_V1';status=$heartbeat.status;generated_utc=Iso-Now;sequence=$sequence;integrity=$integrity;v3_entry_summary=$entrySummary;invalidation_summary=$summaryPayload;per_trade_rows=@($perTrade).Count};Atomic-Json (Join-Path (Join-Path $output 'daily') ((Get-Date).ToUniversalTime().ToString('yyyyMMdd')+'-snapshot.json')) $snapshot
}catch{$errorReceipt=[ordered]@{schema='SOLTRADE_V3_FORWARD_EVALUATOR_ERROR_V1';status='EVALUATOR_ERROR';utc=Iso-Now;message=$_.Exception.Message;order_capability=$false};Atomic-Json (Join-Path $statusDir 'heartbeat.json') $errorReceipt;throw}finally{if($null-ne $lock){$lock.Dispose()}}
