#property strict
#property version "1.000"
#property description "V31 custom-symbol real tick qualification; no trading and no P&L"

input datetime DataFrom=D'2018.01.01 00:00:00';
input datetime EligibleFrom=D'2018.02.05 10:05:00';
input datetime BoundTo=D'2025.01.01 00:00:00';
input long ExpectedTicks=0;
input string CanonicalSymbol="EURUSD";
input string OutputRoot="SolTrade\\Phase6\\V31ExternalQualification\\EURUSD";
long g_ticks=0,g_warmup_ticks=0,g_eligible_ticks=0,g_zero_spread=0,g_m1=0,g_h1=0,g_m1_mismatch=0,g_h1_mismatch=0,g_spread_samples=0,g_duplicate_msc=0,g_backward_msc=0;
long g_year_ticks[7],g_year_m1[7],g_year_h1[7],g_prev_msc=0,g_h1_before_eligible=0;
datetime g_first=0,g_last=0,g_minute=0,g_hour=0;double g_m1_o=0,g_m1_h=0,g_m1_l=0,g_m1_c=0,g_h1_o=0,g_h1_h=0,g_h1_l=0,g_h1_c=0,g_spread_sum=0,g_spread_max=0;
int g_gaps=INVALID_HANDLE;bool g_ok=false,g_outside=false;
string ResearchSymbol(const string canonical){return canonical=="EURUSD"?"EURUSD.V31":canonical=="GBPUSD"?"GBPUSD.V31":canonical=="AUDUSD"?"AUDUSD.V31":canonical=="NZDUSD"?"NZDUSD.V31":canonical=="USDCAD"?"USDCAD.V31":canonical=="USDCHF"?"USDCHF.V31":canonical=="USDJPY"?"USDJPY.V31":"";}
string TS(datetime x){return x>0?TimeToString(x,TIME_DATE|TIME_SECONDS):"NONE";}int YearIndex(datetime x){MqlDateTime d;TimeToStruct(x,d);return d.year>=2018&&d.year<=2024?d.year-2018:-1;}datetime FloorMinute(datetime x){return x-x%60;}datetime FloorHour(datetime x){return x-x%3600;}bool Same(double a,double b){return MathAbs(a-b)<=SymbolInfoDouble(_Symbol,SYMBOL_POINT)/2.0;}
void CompareBar(ENUM_TIMEFRAMES tf,datetime opening,double o,double h,double l,double c,long &mismatches){int shift=iBarShift(_Symbol,tf,opening,true);if(shift<0||iTime(_Symbol,tf,shift)!=opening||!Same(iOpen(_Symbol,tf,shift),o)||!Same(iHigh(_Symbol,tf,shift),h)||!Same(iLow(_Symbol,tf,shift),l)||!Same(iClose(_Symbol,tf,shift),c))mismatches++;}
void CloseMinute(){if(g_minute<=0)return;CompareBar(PERIOD_M1,g_minute,g_m1_o,g_m1_h,g_m1_l,g_m1_c,g_m1_mismatch);int y=YearIndex(g_minute);if(y>=0)g_year_m1[y]++;g_m1++;}
void CloseHour(){if(g_hour<=0)return;CompareBar(PERIOD_H1,g_hour,g_h1_o,g_h1_h,g_h1_l,g_h1_c,g_h1_mismatch);int y=YearIndex(g_hour);if(y>=0)g_year_h1[y]++;g_h1++;if(g_hour<EligibleFrom)g_h1_before_eligible++;}
void StartMinute(datetime m,double bid){g_minute=m;g_m1_o=bid;g_m1_h=bid;g_m1_l=bid;g_m1_c=bid;}void StartHour(datetime h,double bid){g_hour=h;g_h1_o=bid;g_h1_h=bid;g_h1_l=bid;g_h1_c=bid;}
int OnInit(){if(!MQLInfoInteger(MQL_TESTER)||MQLInfoInteger(MQL_OPTIMIZATION)||(int)TerminalInfoInteger(TERMINAL_BUILD)!=6090||AccountInfoString(ACCOUNT_SERVER)!="FPMarketsSC-Demo"||DataFrom!=D'2018.01.01 00:00:00'||EligibleFrom!=D'2018.02.05 10:05:00'||BoundTo!=D'2025.01.01 00:00:00'||ExpectedTicks<=0||_Symbol!=ResearchSymbol(CanonicalSymbol)||(bool)SymbolInfoInteger(_Symbol,SYMBOL_CUSTOM)!=true)return INIT_PARAMETERS_INCORRECT;g_gaps=FileOpen(OutputRoot+"\\tick-gaps.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(g_gaps==INVALID_HANDLE)return INIT_FAILED;FileWrite(g_gaps,"schema","canonical_symbol","research_symbol","previous_tick_msc","current_tick_msc","gap_milliseconds");g_ok=true;return INIT_SUCCEEDED;}
void OnTick(){MqlTick tick;if(!SymbolInfoTick(_Symbol,tick)||tick.time<DataFrom)return;if(tick.time>=BoundTo){g_outside=true;return;}if(g_prev_msc>0){if(tick.time_msc<g_prev_msc)g_backward_msc++;else if(tick.time_msc==g_prev_msc)g_duplicate_msc++;if(tick.time_msc-g_prev_msc>3600000)FileWrite(g_gaps,"SOLTRADE_PHASE6_V31_TICK_GAP_V1",CanonicalSymbol,_Symbol,g_prev_msc,tick.time_msc,tick.time_msc-g_prev_msc);}g_prev_msc=tick.time_msc;if(g_first==0)g_first=tick.time;g_last=tick.time;g_ticks++;int y=YearIndex(tick.time);if(y>=0)g_year_ticks[y]++;if(tick.time<EligibleFrom)g_warmup_ticks++;else g_eligible_ticks++;double point=SymbolInfoDouble(_Symbol,SYMBOL_POINT),spread=point>0?(tick.ask-tick.bid)/point:0;g_spread_samples++;g_spread_sum+=spread;if(spread>g_spread_max)g_spread_max=spread;if(spread<=0)g_zero_spread++;datetime minute=FloorMinute(tick.time),hour=FloorHour(tick.time);if(g_minute==0)StartMinute(minute,tick.bid);else if(minute!=g_minute){CloseMinute();StartMinute(minute,tick.bid);}else{g_m1_h=MathMax(g_m1_h,tick.bid);g_m1_l=MathMin(g_m1_l,tick.bid);g_m1_c=tick.bid;}if(g_hour==0)StartHour(hour,tick.bid);else if(hour!=g_hour){CloseHour();StartHour(hour,tick.bid);}else{g_h1_h=MathMax(g_h1_h,tick.bid);g_h1_l=MathMin(g_h1_l,tick.bid);g_h1_c=tick.bid;}}
bool WriteSummary(){CloseMinute();CloseHour();int h=FileOpen(OutputRoot+"\\qualification-summary.csv",FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,',');if(h==INVALID_HANDLE)return false;FileWrite(h,"field","value");FileWrite(h,"schema","SOLTRADE_PHASE6_V31_EXTERNAL_QUALIFICATION_V1");FileWrite(h,"canonical_symbol",CanonicalSymbol);FileWrite(h,"research_symbol",_Symbol);FileWrite(h,"model","EVERY_TICK_BASED_ON_REAL_TICKS");FileWrite(h,"data_from",TS(DataFrom));FileWrite(h,"eligible_from",TS(EligibleFrom));FileWrite(h,"bound_to_exclusive",TS(BoundTo));FileWrite(h,"expected_tick_count",ExpectedTicks);FileWrite(h,"tick_count",g_ticks);FileWrite(h,"warmup_tick_count",g_warmup_ticks);FileWrite(h,"eligible_tick_count",g_eligible_ticks);FileWrite(h,"h1_bars_before_eligible",g_h1_before_eligible);FileWrite(h,"first_tick",TS(g_first));FileWrite(h,"final_tick",TS(g_last));FileWrite(h,"m1_count",g_m1);FileWrite(h,"h1_count",g_h1);FileWrite(h,"m1_mismatches",g_m1_mismatch);FileWrite(h,"h1_mismatches",g_h1_mismatch);FileWrite(h,"duplicate_timestamp_msc_retained",g_duplicate_msc);FileWrite(h,"backward_timestamp_msc",g_backward_msc);FileWrite(h,"spread_samples",g_spread_samples);FileWrite(h,"zero_or_negative_spread_samples",g_zero_spread);FileWrite(h,"mean_spread_points",g_spread_samples>0?g_spread_sum/g_spread_samples:0);FileWrite(h,"maximum_spread_points",g_spread_max);FileWrite(h,"digits",(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS));FileWrite(h,"point",DoubleToString(SymbolInfoDouble(_Symbol,SYMBOL_POINT),10));FileWrite(h,"contract_size",DoubleToString(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_CONTRACT_SIZE),2));for(int i=0;i<7;i++){string year=IntegerToString(2018+i);FileWrite(h,"ticks_"+year,g_year_ticks[i]);FileWrite(h,"m1_"+year,g_year_m1[i]);FileWrite(h,"h1_"+year,g_year_h1[i]);}FileWrite(h,"orders_or_positions","ZERO");FileWrite(h,"pnl_calculated","NO");bool pass=g_ok&&!g_outside&&g_ticks==ExpectedTicks&&g_warmup_ticks>0&&g_eligible_ticks>0&&g_first>0&&g_last>0&&g_h1_before_eligible>=300&&g_m1_mismatch==0&&g_h1_mismatch==0&&g_backward_msc==0&&g_spread_samples==g_ticks;for(int i=0;i<7;i++)pass=pass&&g_year_ticks[i]>0&&g_year_m1[i]>0&&g_year_h1[i]>0;FileWrite(h,"status",pass?"PASS":"FAIL");FileClose(h);return pass;}
double OnTester(){if(g_gaps!=INVALID_HANDLE)FileFlush(g_gaps);return WriteSummary()?1:0;}void OnDeinit(const int reason){if(g_gaps!=INVALID_HANDLE)FileClose(g_gaps);}
