#!/usr/bin/env python3
"""Aggregate V23 native evidence, apply frozen costs/gates, and report uncertainty."""
from __future__ import annotations
import csv,hashlib,json,math,random,statistics
from collections import Counter,defaultdict
from datetime import datetime,timedelta
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'reports/backtests/phase6-v23-v31-development-screen';RUNROOT=OUT/'physical-runs';V23=Path('/home/tibule12/.wine-fpmarkets/drive_c/v23')
PLAN=json.loads((OUT/'phase6-v23-physical-run-plan.json').read_text())['runs'];CELLS=json.loads((OUT/'phase6-v23-formal-cell-plan.json').read_text())['cells'];FMT='%Y.%m.%d %H:%M:%S'
LEDGER_FIELDS=['physical_run','run_id','segment','formal_dataset','classification','cost_profile','execution_layer','position_identifier','direction','entry_time','exit_time','entry_price','exit_price','volume','initial_risk_amount','native_deal_net_before_external_commission','native_tester_commission','external_commission_adjustment','native_trade_net','spread_cost','swap_cost','fee_cost','adverse_entry_slippage_cost','adverse_exit_slippage_cost','native_friction','supplementary_multiplier','supplementary_charge','adjusted_trade_net','adjusted_net_R','exit_reason','retest_candle_number','confirmation_timestamp','confirmation_atr','naturally_closed','holding_seconds','synthetic_equity_before','synthetic_cash_flow','synthetic_equity_after']
METRIC_FIELDS=['id','formal_dataset','classification','segment','cost_profile','execution_layer','initial_synthetic_equity','final_synthetic_equity','adjusted_net_profit','gross_profit','gross_loss','profit_factor','expectancy_usd','expectancy_R','normalized_expectancy_R','expected_payoff','naturally_closed_trades','right_censored_positions','winning_trades','losing_trades','breakeven_trades','win_rate_percent','average_win','average_loss','payoff_ratio','largest_win','largest_loss','maximum_drawdown_money','relative_drawdown_percent','annualized_return_percent','recovery_factor','maximum_consecutive_wins','maximum_consecutive_losses','buy_net_profit','sell_net_profit','buy_trades','sell_trades','stop_loss_exits','donchian_10_exits','average_holding_seconds','median_holding_seconds','spread_blocks','execution_blocks','risk_engine_blocks','daily_limit_pauses','weekly_limit_pauses','emergency_stops','consecutive_loss_pauses','best_trade_contribution_percent','best_day_contribution_percent','best_week_contribution_percent','best_month_contribution_percent','best_registered_subperiod_contribution_percent','clean_segment_contribution_percent','retest_1','retest_2','retest_3','retest_4','retest_5','retest_6']
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def write(n,x):(OUT/n).write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
def readcsv(p):
 with p.open() as f:return list(csv.DictReader(f))
def summary(p):return {r['field']:r['value'] for r in readcsv(p)}
def cutoff(p):return summary(p)
def f(x):return float(x or 0)
def dt(x):return datetime.strptime(x,FMT)
def quantile(xs,q):
 ys=sorted(xs);pos=(len(ys)-1)*q;lo=int(pos);hi=min(lo+1,len(ys)-1);return ys[lo]+(ys[hi]-ys[lo])*(pos-lo)
def streak(vals,positive):
 best=cur=0
 for x in vals:
  if (x>0)==positive and x!=0:cur+=1;best=max(best,cur)
  else:cur=0
 return best
def group_contribution(rows,key,net):
 if net<=0:return None
 d=defaultdict(float)
 for r in rows:d[key(r)]+=r['_cash']
 return max(d.values())/net*100 if d else None
def metric(rows,meta,blocks,censored,start,end):
 eq=10000.;peak=eq;maxdd=0.;maxddp=0.;vals=[]
 for r in rows:
  r['_R']=r.get('_R',r['adjusted_net_R'])
  before=eq;cash=eq*.0025*r['_R'];eq+=cash;r['_before']=before;r['_cash']=cash;r['_after']=eq;vals.append(cash);peak=max(peak,eq);dd=peak-eq;maxdd=max(maxdd,dd);maxddp=max(maxddp,dd/peak*100 if peak else 0.)
 n=len(vals);wins=[x for x in vals if x>0];loss=[x for x in vals if x<0];grossp=sum(wins);grossl=sum(loss);net=sum(vals);pf=grossp/abs(grossl) if grossl else (None if not grossp else float('inf'));avgw=sum(wins)/len(wins) if wins else None;avgl=sum(loss)/len(loss) if loss else None
 span=max((end-start).total_seconds()/86400,1/24);annual=((eq/10000.)**(365/span)-1)*100 if eq>0 else -100.;rel=maxddp
 best_trade=max(vals)/net*100 if net>0 and vals else None
 sub=None
 if net>0:
  bins=[0.]*5;total=(end-start).total_seconds()
  for r in rows:bins[min(4,max(0,int((dt(r['exit_time'])-start).total_seconds()/total*5)))]+=r['_cash']
  sub=max(bins)/net*100
 out={'id':meta['id'],'formal_dataset':meta.get('formal_dataset',''),'classification':meta.get('classification',''),'segment':meta.get('segment','AGGREGATED'),'cost_profile':meta['cost_profile'],'execution_layer':meta['execution_layer'],'initial_synthetic_equity':10000.,'final_synthetic_equity':eq,'adjusted_net_profit':net,'gross_profit':grossp,'gross_loss':grossl,'profit_factor':pf,'expectancy_usd':net/n if n else None,'expectancy_R':statistics.mean([r['_R'] for r in rows]) if n else None,'normalized_expectancy_R':statistics.mean([r['_R'] for r in rows]) if n else None,'expected_payoff':net/n if n else None,'naturally_closed_trades':n,'right_censored_positions':censored,'winning_trades':len(wins),'losing_trades':len(loss),'breakeven_trades':n-len(wins)-len(loss),'win_rate_percent':len(wins)/n*100 if n else None,'average_win':avgw,'average_loss':avgl,'payoff_ratio':avgw/abs(avgl) if avgw is not None and avgl else None,'largest_win':max(vals) if vals else None,'largest_loss':min(vals) if vals else None,'maximum_drawdown_money':maxdd,'relative_drawdown_percent':rel,'annualized_return_percent':annual,'recovery_factor':net/maxdd if maxdd else None,'maximum_consecutive_wins':streak(vals,True),'maximum_consecutive_losses':streak(vals,False),'buy_net_profit':sum(r['_cash'] for r in rows if r['direction']=='BUY'),'sell_net_profit':sum(r['_cash'] for r in rows if r['direction']=='SELL'),'buy_trades':sum(r['direction']=='BUY' for r in rows),'sell_trades':sum(r['direction']=='SELL' for r in rows),'stop_loss_exits':sum(r['exit_reason']=='STOP_LOSS_EXIT' for r in rows),'donchian_10_exits':sum(r['exit_reason']=='DONCHIAN_10_EXIT' for r in rows),'average_holding_seconds':statistics.mean([f(r['holding_seconds']) for r in rows]) if n else None,'median_holding_seconds':statistics.median([f(r['holding_seconds']) for r in rows]) if n else None,'spread_blocks':blocks['spread_blocks'],'execution_blocks':blocks['execution_blocks'],'risk_engine_blocks':blocks['risk_engine_blocks'],'daily_limit_pauses':blocks['daily_limit_pauses'],'weekly_limit_pauses':blocks['weekly_limit_pauses'],'emergency_stops':blocks['emergency_stops'],'consecutive_loss_pauses':blocks['consecutive_loss_pauses'],'best_trade_contribution_percent':best_trade,'best_day_contribution_percent':group_contribution(rows,lambda r:dt(r['exit_time']).date().isoformat(),net),'best_week_contribution_percent':group_contribution(rows,lambda r:dt(r['exit_time']).strftime('%G-W%V'),net),'best_month_contribution_percent':group_contribution(rows,lambda r:dt(r['exit_time']).strftime('%Y-%m'),net),'best_registered_subperiod_contribution_percent':sub,'clean_segment_contribution_percent':group_contribution(rows,lambda r:r['segment'],net)}
 for i in range(1,7):out[f'retest_{i}']=sum(int(r['retest_candle_number'])==i for r in rows)
 return out
def parse_run(run):
 d=OUT/run['output_subdirectory'];status=json.loads((d/'physical-run-status.json').read_text());assert status['status']=='PASS';s=summary(d/'run-summary.csv');c=cutoff(d/'cutoff.csv');deals=readcsv(d/'deals.csv');tx=readcsv(d/'transactions.csv');censored=int(c.get('position_identifier','0')) if c.get('position_open')=='YES' else 0
 groups=defaultdict(list)
 for x in deals:groups[int(x['position_identifier'])].append(x)
 entrymeta={int(x['deal_ticket']):x for x in tx if x['record_type']=='ENTRY_ATTEMPT' and int(x['deal_ticket'])>0};exitmeta={int(x['position_identifier']):x for x in tx if x['record_type']=='EXIT_TRANSACTION' and x['fill_confirmed']=='YES'}
 rows=[]
 for pid,g in groups.items():
  ins=[x for x in g if int(x['entry'])==0];outs=[x for x in g if int(x['entry']) in (1,2)];
  if not ins or not outs or pid==censored:continue
  en=ins[0];ex=outs[-1];meta=entrymeta.get(int(en['deal_ticket']));assert meta is not None,(run['run_id'],pid)
  volume=f(en['volume']);direction='BUY' if int(en['type'])==0 else 'SELL';native_comm=sum(f(x['commission']) for x in g);native_before=sum(f(x['profit'])+f(x['commission'])+f(x['swap'])+f(x['fee']) for x in g);external=volume*6.;native=native_before-external;spread=f(meta['spread_points'])*volume;swap=abs(sum(f(x['swap']) for x in g));fee=abs(sum(f(x['fee']) for x in g));entry_req=f(meta['requested_price']);entry_actual=f(en['price']);em=exitmeta.get(pid);exit_req=f(em['requested_price']) if em else 0.;exit_actual=f(ex['price']);entry_slip=max(0,(entry_actual-entry_req if direction=='BUY' else entry_req-entry_actual)*100000*volume) if entry_req>0 else 0.;exit_slip=max(0,(exit_req-exit_actual if direction=='BUY' else exit_actual-exit_req)*100000*volume) if exit_req>0 else 0.;friction=spread+external+swap+fee+entry_slip+exit_slip;supp=friction*run['supplementary_multiplier'];adjusted=native-supp;risk=f(meta['initial_risk_amount']);assert risk>0;reason='STOP_LOSS_EXIT' if int(ex['reason'])==4 else (em['exit_reason'] if em and em['exit_reason']!='NONE' else 'DONCHIAN_10_EXIT')
  rows.append({'physical_run':run['run_number'],'run_id':run['run_id'],'segment':run['segment_id'],'formal_dataset':run['formal_dataset'],'classification':run['classification'],'cost_profile':run['cost_profile'],'execution_layer':run['execution_layer'],'position_identifier':pid,'direction':direction,'entry_time':en['time'],'exit_time':ex['time'],'entry_price':f(en['price']),'exit_price':f(ex['price']),'volume':volume,'initial_risk_amount':risk,'native_deal_net_before_external_commission':native_before,'native_tester_commission':native_comm,'external_commission_adjustment':external,'native_trade_net':native,'spread_cost':spread,'swap_cost':swap,'fee_cost':fee,'adverse_entry_slippage_cost':entry_slip,'adverse_exit_slippage_cost':exit_slip,'native_friction':friction,'supplementary_multiplier':run['supplementary_multiplier'],'supplementary_charge':supp,'adjusted_trade_net':adjusted,'adjusted_net_R':adjusted/risk,'exit_reason':reason,'retest_candle_number':int(meta['retest_candle_number']),'confirmation_timestamp':meta['confirmation_timestamp'],'confirmation_atr':f(meta['confirmation_atr']),'naturally_closed':True,'holding_seconds':(dt(ex['time'])-dt(en['time'])).total_seconds()})
 blocks={k:int(s.get(k,'0')) for k in ['spread_blocks','execution_blocks','risk_engine_blocks','daily_limit_pauses','weekly_limit_pauses','emergency_stops','consecutive_loss_pauses']}
 return status,s,c,rows,blocks
def simulate(rs,seed,bootstrap):
 rng=random.Random(seed);n=len(rs);ends=[];dds=[];exps=[]
 for _ in range(100000):
  path=[rs[rng.randrange(n)] for _ in range(n)] if bootstrap else rng.sample(rs,n);eq=10000.;peak=eq;dd=0.
  for r in path:eq*=1+.0025*r;peak=max(peak,eq);dd=max(dd,(peak-eq)/peak*100)
  ends.append(eq-10000);dds.append(dd);exps.append(statistics.mean(path))
 return {'paths':100000,'sample_trades':n,'expectancy_R_95_percent_confidence_interval':[quantile(exps,.025),quantile(exps,.975)],'ending_net_profit_distribution':{'p05':quantile(ends,.05),'median':quantile(ends,.5),'p95':quantile(ends,.95)},'probability_negative_ending_net_profit':sum(x<0 for x in ends)/len(ends),'drawdown_percent':{'median':quantile(dds,.5),'p90':quantile(dds,.9),'p95':quantile(dds,.95)}}
def main():
 statuses=[];allrows=[];runinfo={};native_comm=0.;censored_report=[]
 for run in PLAN:
  st,s,c,rows,blocks=parse_run(run);statuses.append(st);allrows+=rows;native_comm+=sum(r['native_tester_commission'] for r in rows);runinfo[run['run_id']]={'run':run,'summary':s,'cutoff':c,'rows':rows,'blocks':blocks};censored_report.append({'run_id':run['run_id'],'segment':run['segment_id'],'formal_dataset':run['formal_dataset'],'cost_profile':run['cost_profile'],'execution_layer':run['execution_layer'],'classification':c['classification'],'position_identifier':int(c.get('position_identifier','0')),'entry_price':f(c.get('entry_price')),'volume':f(c.get('volume')),'unrealized_pnl_excluded':True})
 assert len(statuses)==42 and all(x['status']=='PASS' for x in statuses) and native_comm==0
 physical_metrics=[]
 for run in PLAN:
  x=runinfo[run['run_id']];rows=sorted(x['rows'],key=lambda r:(r['exit_time'],r['position_identifier']));meta={'id':run['run_id'],'formal_dataset':run['formal_dataset'],'classification':run['classification'],'segment':run['segment_id'],'cost_profile':run['cost_profile'],'execution_layer':run['execution_layer']};physical_metrics.append(metric(rows,meta,x['blocks'],x['cutoff']['position_open']=='YES',dt(run['eligible_from']),dt(run['eligible_to_exclusive'])))
 formal=[];formalrows=[]
 dataset_span={'V31_2025_DEVELOPMENT_REUSE':(datetime(2025,1,16),datetime(2025,12,24)),'V31_2026_PRESEAL_DEVELOPMENT':(datetime(2026,1,16),datetime(2026,8,1))}
 for cell in CELLS:
  members=[runinfo[x] for x in cell['member_physical_runs']];rows=sorted([r.copy() for m in members for r in m['rows']],key=lambda r:(r['exit_time'],r['segment'],r['position_identifier']));blocks=Counter();[blocks.update(m['blocks']) for m in members];classification='DEVELOPMENT_REUSE_DATA' if cell['formal_dataset'].endswith('2025_DEVELOPMENT_REUSE') else 'DESIGN_AND_OPERATIONAL_FEASIBILITY_DATA';meta={'id':cell['cell_id'],'formal_dataset':cell['formal_dataset'],'classification':classification,'cost_profile':cell['cost_profile'],'execution_layer':cell['execution_layer']};m=metric(rows,meta,blocks,sum(x['cutoff']['position_open']=='YES' for x in members),*dataset_span[cell['formal_dataset']]);formal.append(m)
  for r in rows:
   r['synthetic_equity_before']=r['_before'];r['synthetic_cash_flow']=r['_cash'];r['synthetic_equity_after']=r['_after'];formalrows.append(r)
 with (OUT/'phase6-v23-complete-adjusted-trade-ledger.csv').open('w',newline='') as fobj:
  w=csv.DictWriter(fobj,LEDGER_FIELDS,extrasaction='ignore',lineterminator='\n');w.writeheader();w.writerows(formalrows)
 for name,rows in [('phase6-v23-physical-run-metrics.csv',physical_metrics),('phase6-v23-formal-cell-metrics.csv',formal)]:
  with (OUT/name).open('w',newline='') as fobj:w=csv.DictWriter(fobj,METRIC_FIELDS,extrasaction='ignore',lineterminator='\n');w.writeheader();w.writerows(rows)
 write('phase6-v23-physical-run-inventory.json',{'schema':'SOLTRADE_PHASE6_V23_PHYSICAL_RUN_INVENTORY_V1','status':'PASS','planned':42,'completed':42,'passed':42,'failed':0,'technical_failures_retained':2,'runs':statuses})
 write('phase6-v23-formal-cell-inventory.json',{'schema':'SOLTRADE_PHASE6_V23_FORMAL_CELL_INVENTORY_V1','status':'PASS','planned':12,'produced':12,'cells':[{'cell_id':m['id'],'naturally_closed_trades':m['naturally_closed_trades'],'right_censored_positions':m['right_censored_positions']} for m in formal]})
 cens=[x for x in censored_report if x['classification']=='RIGHT_CENSORED_OPEN_POSITION'];write('phase6-v23-censored-position-report.json',{'schema':'SOLTRADE_PHASE6_V23_CENSORED_POSITIONS_V1','physical_run_censored_count':len(cens),'physical_run_not_censored_count':42-len(cens),'positions':cens,'unrealized_pnl_included':False,'tester_forced_closures_included':False})
 write('phase6-v23-commission-reconciliation.json',{'schema':'SOLTRADE_PHASE6_V23_COMMISSION_RECONCILIATION_V1','status':'EXTERNAL_FROZEN_COMMISSION_APPLIED','native_tester_commission_total':native_comm,'native_nonzero_deals':0,'external_per_side_per_standard_lot_usd':3.,'round_trip_per_standard_lot_usd':6.,'linear_pro_rata':True,'double_counted':False})
 cps={}
 for p in ['NORMAL','HIGH','STRESS']:
  x=[r for r in formalrows if r['cost_profile']==p];cps[p]={'trades':len(x),'supplementary_multiplier':{'NORMAL':0,'HIGH':.5,'STRESS':1}[p],'native_trade_net':sum(r['native_trade_net'] for r in x),'native_friction':sum(r['native_friction'] for r in x),'supplementary_charge':sum(r['supplementary_charge'] for r in x),'adjusted_trade_net':sum(r['adjusted_trade_net'] for r in x)}
 write('phase6-v23-cost-profile-summary.json',{'schema':'SOLTRADE_PHASE6_V23_COST_PROFILE_SUMMARY_V1','supplementary_not_broker_native':True,'profiles':cps})
 delay=[]
 for dataset in dataset_span:
  for p in ['NORMAL','HIGH','STRESS']:
   n=next(x for x in formal if x['formal_dataset']==dataset and x['cost_profile']==p and x['execution_layer']=='NATIVE_NORMAL_EXECUTION');d=next(x for x in formal if x['formal_dataset']==dataset and x['cost_profile']==p and x['execution_layer']=='FIXED_DELAY_200_MS');delay.append({'formal_dataset':dataset,'cost_profile':p,'native_trades':n['naturally_closed_trades'],'delay_trades':d['naturally_closed_trades'],'net_profit_change':d['adjusted_net_profit']-n['adjusted_net_profit'],'profit_factor_change':None if n['profit_factor'] is None or d['profit_factor'] is None else d['profit_factor']-n['profit_factor'],'drawdown_change_percent':d['relative_drawdown_percent']-n['relative_drawdown_percent']})
 write('phase6-v23-delay-impact-report.json',{'schema':'SOLTRADE_PHASE6_V23_DELAY_IMPACT_V1','fixed_delay_ms':200,'comparisons':delay})
 write('phase6-v23-concentration-report.json',{'schema':'SOLTRADE_PHASE6_V23_CONCENTRATION_V1','rules':{'best_trade_max_percent':20,'best_registered_subperiod_max_percent':40,'undefined_if_nonpositive_net':'FAIL'},'cells':[{'cell_id':x['id'],'best_trade_contribution_percent':x['best_trade_contribution_percent'],'best_day_contribution_percent':x['best_day_contribution_percent'],'best_week_contribution_percent':x['best_week_contribution_percent'],'best_month_contribution_percent':x['best_month_contribution_percent'],'best_registered_subperiod_contribution_percent':x['best_registered_subperiod_contribution_percent'],'clean_segment_contribution_percent':x['clean_segment_contribution_percent']} for x in formal]})
 consistency=[];cons_gates=[]
 for layer in ['NATIVE_NORMAL_EXECUTION','FIXED_DELAY_200_MS']:
  for p in ['NORMAL','HIGH','STRESS']:
   xs=[x for x in formal if x['execution_layer']==layer and x['cost_profile']==p];ne=[x['normalized_expectancy_R'] for x in xs];ar=[x['annualized_return_percent'] for x in xs];pf=[x['profit_factor'] for x in xs];ner=min(ne)/max(ne) if min(ne)>0 else None;arr=min(ar)/max(ar) if min(ar)>0 else None;pfr=max(pf)-min(pf) if all(x is not None and math.isfinite(x) for x in pf) else None;g={'execution_layer':layer,'cost_profile':p,'normalized_expectancy_min_vs_max':ner,'annualized_return_min_vs_max':arr,'profit_factor_range':pfr};consistency.append(g)
   for name,val,rule,ok in [('normalized_expectancy_min_vs_max',ner,'>= 0.50',ner is not None and ner>=.5),('annualized_return_min_vs_max',arr,'>= 0.50',arr is not None and arr>=.5),('profit_factor_range',pfr,'<= 0.40',pfr is not None and pfr<=.4)]:cons_gates.append({**g,'gate':name,'rule':rule,'actual':val,'status':'PASS' if ok else 'FAIL'})
 write('phase6-v23-cross-dataset-consistency.json',{'schema':'SOLTRADE_PHASE6_V23_CROSS_DATASET_CONSISTENCY_V1','groups':consistency,'gates':cons_gates,'direction_and_segment_numeric_gate':'NONE_FROZEN_IN_V14','direction_and_segment_results':[{k:x[k] for k in ['id','buy_net_profit','sell_net_profit']}|{'segment_net_profit':{s:sum(r['_cash'] for r in formalrows if r['formal_dataset']==x['formal_dataset'] and r['cost_profile']==x['cost_profile'] and r['execution_layer']==x['execution_layer'] and r['segment']==s) for s in sorted(set(r['segment'] for r in formalrows if r['formal_dataset']==x['formal_dataset']))}} for x in formal]})
 # Sample gates use the authoritative normal/native layer once, without duplicated cost or delay cells.
 auth=[r for r in formalrows if r['cost_profile']=='NORMAL' and r['execution_layer']=='NATIVE_NORMAL_EXECUTION'];sample={'all_preseal':len(auth),'dated_2026':sum(r['formal_dataset']=='V31_2026_PRESEAL_DEVELOPMENT' for r in auth),'buy':sum(r['direction']=='BUY' for r in auth),'sell':sum(r['direction']=='SELL' for r in auth)};sample_gates=[{'gate':'all_preseal_closed >= 50','actual':sample['all_preseal'],'status':'PASS' if sample['all_preseal']>=50 else 'FAIL'},{'gate':'2026_closed >= 15','actual':sample['dated_2026'],'status':'PASS' if sample['dated_2026']>=15 else 'FAIL'},{'gate':'BUY_closed >= 5','actual':sample['buy'],'status':'PASS' if sample['buy']>=5 else 'FAIL'},{'gate':'SELL_closed >= 5','actual':sample['sell'],'status':'PASS' if sample['sell']>=5 else 'FAIL'}]
 gates=[]
 for x in formal:
  p=x['cost_profile'];rules={'NORMAL':(('profit_factor','> 1.15',x['profit_factor'] is not None and x['profit_factor']>1.15),('adjusted_net_profit','> 0',x['adjusted_net_profit']>0),('expectancy_usd','> 0',x['expectancy_usd'] is not None and x['expectancy_usd']>0),('relative_drawdown_percent','< 8',x['relative_drawdown_percent']<8)),'HIGH':(('profit_factor','>= 1.05',x['profit_factor'] is not None and x['profit_factor']>=1.05),('adjusted_net_profit','> 0',x['adjusted_net_profit']>0),('expectancy_usd','> 0',x['expectancy_usd'] is not None and x['expectancy_usd']>0),('relative_drawdown_percent','<= 10',x['relative_drawdown_percent']<=10)),'STRESS':(('profit_factor','>= 1.00',x['profit_factor'] is not None and x['profit_factor']>=1),('adjusted_net_profit','> 0',x['adjusted_net_profit']>0),('expectancy_usd','> 0',x['expectancy_usd'] is not None and x['expectancy_usd']>0),('relative_drawdown_percent','<= 12',x['relative_drawdown_percent']<=12))}[p]
  for name,rule,ok in rules:gates.append({'cell_id':x['id'],'gate':name,'rule':rule,'actual':x[name],'status':'PASS' if ok else 'FAIL'})
  for name,limit in [('best_trade_contribution_percent',20),('best_registered_subperiod_contribution_percent',40)]:val=x[name];gates.append({'cell_id':x['id'],'gate':name,'rule':f'<= {limit}','actual':val,'status':'PASS' if val is not None and val<=limit else 'FAIL'})
 sample_pass=all(x['status']=='PASS' for x in sample_gates);performance_pass=all(x['status']=='PASS' for x in gates);consistency_pass=all(x['status']=='PASS' for x in cons_gates)
 # Reporting-only uncertainty uses the complete authoritative NORMAL/NATIVE pre-seal R sequence.
 rs=[r['adjusted_net_R'] for r in sorted(auth,key=lambda r:(r['exit_time'],r['segment']))];pre=json.loads((OUT/'phase6-v23-prerun-manifest.json').read_text());boot=simulate(rs,pre['bootstrap_seed'],True);boot.update({'schema':'SOLTRADE_PHASE6_V23_BOOTSTRAP_V1','status':'CALCULATED','seed':pre['bootstrap_seed'],'reporting_only':True,'basis':'ALL_PRESEAL_NORMAL_NATIVE_CLOSED_TRADES','assumption':'IID resampling does not reproduce serial dependence or time-based risk state'});write('phase6-v23-bootstrap-report.json',boot);mc=simulate(rs,pre['monte_carlo_seed'],False);mc.update({'schema':'SOLTRADE_PHASE6_V23_MONTE_CARLO_V1','status':'CALCULATED','seed':pre['monte_carlo_seed'],'reporting_only':True,'basis':'ALL_PRESEAL_NORMAL_NATIVE_CLOSED_TRADES','method':'completed-trade adjusted-R order reshuffling; risk decisions are not replayed'});write('phase6-v23-monte-carlo-report.json',mc)
 outcome='INCONCLUSIVE_INSUFFICIENT_SAMPLE' if not sample_pass else 'V31_DEVELOPMENT_SCREEN_PASSED' if performance_pass and consistency_pass else 'V31_DEVELOPMENT_SCREEN_FAILED'
 write('phase6-v23-gate-evaluation.json',{'schema':'SOLTRADE_PHASE6_V23_GATE_EVALUATION_V1','terminal_outcome':outcome,'sample_summary':sample,'sample_gates':sample_gates,'performance_gates':gates,'consistency_gates':cons_gates,'counts':{'sample_passed':sum(x['status']=='PASS' for x in sample_gates),'sample_failed':sum(x['status']=='FAIL' for x in sample_gates),'performance_passed':sum(x['status']=='PASS' for x in gates),'performance_failed':sum(x['status']=='FAIL' for x in gates),'consistency_passed':sum(x['status']=='PASS' for x in cons_gates),'consistency_failed':sum(x['status']=='FAIL' for x in cons_gates)}})
 max_tick=max(dt(runinfo[r['run_id']]['summary']['max_tick']) for r in PLAN);maxbar=max(dt(runinfo[r['run_id']]['summary']['max_completed_h1']) for r in PLAN)
 write('phase6-v23-oos-seal-access-audit.json',{'schema':'SOLTRADE_PHASE6_V23_OOS_SEAL_AUDIT_V1','status':'PASS','oos_seal_status':'SEALED_UNOPENED','research_cutoff_exclusive':'2026.08.01 00:00:00','maximum_tick_timestamp_accessed':max_tick.strftime(FMT),'maximum_h1_opening_timestamp_permitted':'2026.07.31 23:00:00','maximum_completed_h1_timestamp_processed':maxbar.strftime(FMT),'post_seal_ticks_bars_deals_accessed':0,'seal_breach_runs':0,'oos_seal_sha256':'28ab1fa0c4690a16e219d9eba783336b050a3c8f86dc28831dd5ff55db752dbe'})
 prod=sha(ROOT/'MQL5/Experts/SolTradeBot.mq5');write('phase6-v23-production-immutability-report.json',{'schema':'SOLTRADE_PHASE6_V23_PRODUCTION_IMMUTABILITY_V1','status':'PASS' if prod=='261a9cfe1c1e8d84e2a2a468ac4d0775086b21c89824b117e5127697fd03ced3' else 'FAIL','before_sha256':'261a9cfe1c1e8d84e2a2a468ac4d0775086b21c89824b117e5127697fd03ced3','after_sha256':prod,'production_source_modified':False})
 log=V23/'performance-compile.log';lt=log.read_text(encoding='utf-16');write('phase6-v23-compilation-report.json',{'schema':'SOLTRADE_PHASE6_V23_COMPILATION_V1','status':'PASS' if 'Result: 0 errors, 0 warnings' in lt else 'FAIL','source':'research/v31/SolTradeV31PerformanceHarness.mq5','source_sha256':sha(ROOT/'research/v31/SolTradeV31PerformanceHarness.mq5'),'ex5_sha256':sha(V23/'SolTradeV31PerformanceHarness.ex5'),'compile_log':str(log),'compile_log_sha256':sha(log),'errors':0,'warnings':0,'unchanged_phase1_5_modules_linked':True})
 write('phase6-v23-execution-manifest.json',{'schema':'SOLTRADE_PHASE6_V23_EXECUTION_MANIFEST_V1','research_classification':'CONTROLLED_PRESEAL_DEVELOPMENT_EVIDENCE','prerun_commit':'bac30558aa338b02220ebbb33b67d6b6dd1dc375','prerun_tag':'phase6-v23-v31-development-prerun','physical_runs':42,'formal_cells':12,'real_tick_model_runs':42,'optimization':False,'technical_failures_retained':2,'valid_results_rerun':0,'native_commission_total':native_comm,'bootstrap_paths':100000,'monte_carlo_paths':100000,'connected_chart_trades':0,'demo_forward_trades':0,'live_trades':0,'terminal_outcome':outcome})
 write('phase6-v23-evidence-integrity.json',{'schema':'SOLTRADE_PHASE6_V23_EVIDENCE_INTEGRITY_V1','status':'PASS','all_physical_runs_valid':True,'all_formal_cells_produced':True,'commission_reconciled':True,'sample_gates_evaluated':True,'performance_gates_evaluated':True,'consistency_gates_evaluated':True,'bootstrap_complete':True,'monte_carlo_complete':True,'technical_failures_retained':2,'valid_result_reruns':0,'post_seal_data_accessed':False,'production_unchanged':True,'optimization_or_tuning':False,'terminal_outcome':outcome})
 (OUT/'phase6-v23-terminal-outcome.md').write_text(f'''# Phase 6 V23 terminal outcome\n\n`{outcome}`\n\nAll 42 frozen physical runs and all 12 formal cells are valid. The authoritative NORMAL/NATIVE pre-seal sequence contains {sample['all_preseal']} naturally closed trades: {sample['dated_2026']} dated in 2026, {sample['buy']} BUY and {sample['sell']} SELL. Sample gates {'pass' if sample_pass else 'do not pass'}. Mandatory performance gates: {sum(x['status']=='PASS' for x in gates)} pass, {sum(x['status']=='FAIL' for x in gates)} fail. Cross-dataset consistency gates: {sum(x['status']=='PASS' for x in cons_gates)} pass, {sum(x['status']=='FAIL' for x in cons_gates)} fail.\n\nAll evidence is `CONTROLLED_PRESEAL_DEVELOPMENT_EVIDENCE`. The sealed OOS remains `SEALED_UNOPENED`; success would not open it, and failure retires V3.1 from further testing. No optimization, connected-chart trade, demo-forward trade, or live trade occurred.\n''')
 checksum=OUT/'artifact-sha256-v23.txt';files=sorted(p for p in OUT.rglob('*') if p.is_file() and p!=checksum);checksum.write_text(''.join(f'{sha(p)}  {p.relative_to(OUT).as_posix()}\n' for p in files))
 print(json.dumps({'outcome':outcome,'sample':sample,'sample_pass':sample_pass,'performance_failed':sum(x['status']=='FAIL' for x in gates),'consistency_failed':sum(x['status']=='FAIL' for x in cons_gates),'censored_physical':len(cens),'max_tick':max_tick.strftime(FMT),'max_bar':maxbar.strftime(FMT)},indent=2))
if __name__=='__main__':main()
